# Recherche des fichiers EAF

In [86]:
import os

def get_all_eaf_files(folder_path):
    """
    Parcours un dossier et ses sous-dossiers
    et retourne la liste de tous les fichiers .eaf
    """
    eaf_files = []

    for root, dirs, files in os.walk(folder_path):
        for file in files:
            if file.lower().endswith(".eaf"):
                full_path = os.path.join(root, file)
                eaf_files.append(full_path)
    
    return eaf_files


# Exemple d'utilisation :
folder = r"C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls"
eaf_list = get_all_eaf_files(folder)

print("Fichiers EAF trouvÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©s :")
for f in eaf_list:
    print(f)

Fichiers EAF trouvÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©s :
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\1NS_11-12_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\2NS_11-12_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\NS_11-12_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\AniN\NS_01-02_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\AniN\NS_03-04_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\AniN\NS_05-06_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\AniN\NS_07-08_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\AniN\NS_09-10_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\AniN\NS_11-12_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\AniN\NS_13-14_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\AniN\NS_15-16_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\Cur\NS_01-02_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\Cur\NS_03-04_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\Cur\NS_05-06_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\Cur\NS_07-08_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\Cur\NS_09-10_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\Cur\NS_11-12_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\Cur\NS_13-14_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\Cur\NS_15-16_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\Pro\NS_01-02_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\Pro\NS_03-04_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\Pro\NS_05-06_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\Pro\NS_07-08_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\Pro\NS_09-10_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\Pro\NS_11-12_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\Pro\NS_13-14_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\Pro\NS_15-16_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\ReS\NS_01-02_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\ReS\NS_03-04_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\ReS\NS_05-06_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\ReS\NS_07-08_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\ReS\NS_09-10_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\ReS\NS_11-12_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\ReS\NS_13-14_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\ReS\NS_15-16_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\03_Nagasaki\軽井沢セミナー用データ\NS_11-12_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\AniN\FO_01-02_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\AniN\FO_03-04_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\AniN\FO_05-06_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\AniN\FO_07-08_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\AniN\FO_09-10_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\AniN\FO_11-12_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\AniN\FO_13-14_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\AniN\FO_15-16_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\Cur\FO_01-02_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\Cur\FO_03-04_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\Cur\FO_05-06_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\Cur\FO_07-08_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\Cur\FO_09-10_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\Cur\FO_11-12_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\Cur\FO_13-14_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\Cur\FO_15-16_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\Pro\FO_01-02_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\Pro\FO_03-04_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\Pro\FO_05-06_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\Pro\FO_07-08_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\Pro\FO_09-10_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\Pro\FO_11-12_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\Pro\FO_13-14_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\Pro\FO_15-16_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\ReS\FO_01-02_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\ReS\FO_03-04_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\ReS\FO_05-06_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\ReS\FO_07-08_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\ReS\FO_09-10_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\ReS\FO_11-12_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\ReS\FO_13-14_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\04_Fukuoka\ReS\FO_15-16_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\IS_13-14_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\IS_13-14_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\AniN\IS_01-02_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\AniN\IS_03-04_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\AniN\IS_05-06_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\AniN\IS_07-08_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\AniN\IS_09-10_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\AniN\IS_11-12_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\AniN\IS_13-14_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\AniN\old\IS_03-04_AniN 2.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\Cur\IS_01-02_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\Cur\IS_03-04_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\Cur\IS_05-06_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\Cur\IS_07-08_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\Cur\IS_09-10_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\Cur\IS_11-12_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\Cur\IS_13-14_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\Pro\IS_01-02_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\Pro\IS_03-04_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\Pro\IS_05-06_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\Pro\IS_07-08_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\Pro\IS_09-10_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\Pro\IS_11-12_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\Pro\IS_13-14_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\ReS\IS_01-02_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\ReS\IS_03-04_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\ReS\IS_05-06_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\ReS\IS_07-08_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\ReS\IS_09-10_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\ReS\IS_11-12_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\05_Ishikawa\ReS\IS_13-14_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\AniN\TY_01-02_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\AniN\TY_03-04_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\AniN\TY_05-06_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\AniN\TY_07-08_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\AniN\TY_09-10_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\AniN\TY_11-12_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\AniN\TY_13-14_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\AniN\TY_15-16_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\Cur\TY_01-02_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\Cur\TY_03-04_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\Cur\TY_05-06_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\Cur\TY_07-08_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\Cur\TY_09-10_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\Cur\TY_11-12_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\Cur\TY_13-14_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\Cur\TY_15-16_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\Pro\TY_01-02_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\Pro\TY_03-04_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\Pro\TY_05-06_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\Pro\TY_07-08_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\Pro\TY_09-10_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\Pro\TY_11-12_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\Pro\TY_13-14_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\Pro\TY_15-16_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\ReS\TY_01-02_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\ReS\TY_03-04_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\ReS\TY_05-06_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\ReS\TY_07-08_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\ReS\TY_09-10_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\ReS\TY_11-12_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\ReS\TY_13-14_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\06_Toyama\ReS\TY_15-16_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\AniN\IK_01-02_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\AniN\IK_03-04_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\AniN\IK_05-06_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\AniN\IK_07-08_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\AniN\IK_09-10_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\AniN\IK_11-12_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\AniN\IK_13-14_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\AniN\IK_15-16_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\AniN\IK_17-18_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\AniN\IK_19-20_AniN.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Cur\IK_01-02_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Cur\IK_03-04_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Cur\IK_05-06_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Cur\IK_07-08_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Cur\IK_09-10_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Cur\IK_11-12_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Cur\IK_13-14_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Cur\IK_15-16_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Cur\IK_17-18_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Cur\IK_19-20_Cur.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Pro\IK_01-02_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Pro\IK_03-04_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Pro\IK_05-06_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Pro\IK_07-08_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Pro\IK_09-10_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Pro\IK_11-12_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Pro\IK_13-14_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Pro\IK_15-16_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Pro\IK_17-18_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\Pro\IK_19-20_Pro.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\ReS\IK_01-02_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\ReS\IK_03-04_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\ReS\IK_05-06_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\ReS\IK_07-08_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\ReS\IK_09-10_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\ReS\IK_11-12_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\ReS\IK_13-14_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\ReS\IK_15-16_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\ReS\IK_17-18_ReS.eaf
C:\Users\Ewan\Desktop\Projet JAPON JSL\corpus jls\07_Ibaraki\ReS\IK_19-20_ReS.eaf

# Definition du dataset unique (train)

In [87]:
# Liste EAF (ancienne liste, fusionnee en train)
TEST_FILES = {
    "FO_13-14_AniN.eaf",
    "FO_05-06_AniN.eaf",
    "FO_15-16_Cur.eaf",
    "FO_05-06_Cur.eaf",
    "IS_05-06_AniN.eaf",
    "IS_01-02_AniN.eaf",
    "IS_07-08_AniN.eaf",
    "IS_09-10_AniN.eaf",
    "IS_13-14_AniN.eaf",
    "IS_09-10_Cur.eaf",
    "IS_05-06_Cur.eaf",
    "IS_07-08_Cur.eaf",
    "IS_13-14_Cur.eaf",
    "IS_01-02_Cur.eaf",
    "IS_03-04_Pro.eaf",
    "IS_13-14_Pro.eaf",
    "IS_09-10_Pro.eaf",
    "IS_07-08_Pro.eaf",
    "IK_03-04_Cur.eaf",
    "IK_15-16_AniN.eaf",
    "NS_11-12_AniN.eaf",
    "NS_05-06_AniN.eaf",
    "NS_01-02_AniN.eaf",
    "NS_11-12_Cur.eaf",
    "NS_05-06_Cur.eaf",
    "NS_01-02_Cur.eaf",
    "TY_05-06_AniN.eaf",
    "TY_07-08_Cur.eaf",
    "TY_05-06_Cur.eaf",
}

keep = TEST_FILES
train = [p for p in eaf_list if os.path.basename(p) in keep]
test = []

# Lecture et extraction EAF

# Chargement des donnees

In [88]:
import os
import xml.etree.ElementTree as ET
import pandas as pd

class EAFReader:
    """
    Lecture d'un fichier ELAN (.eaf)
    Extraction :
    - gloss / value
    - tier
    - linguistic type
    - start time
    - end time
    - duration
    - file (nom du fichier source)
    """

    def __init__(self, path):
        self.path = path
        self.filename = os.path.basename(path)   # <-- AJOUT
        self.tree = ET.parse(path)
        self.root = self.tree.getroot()
        self.time_slots = self._load_time_slots()

    # ---------------------------------------------------------
    # PARTIE 1 ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¦ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â Lecture des time slots
    # ---------------------------------------------------------
    def _load_time_slots(self):
        time_slots = {}
        for ts in self.root.findall(".//TIME_ORDER/TIME_SLOT"):
            ts_id = ts.attrib["TIME_SLOT_ID"]
            ts_value = int(ts.attrib.get("TIME_VALUE", 0))
            time_slots[ts_id] = ts_value
        return time_slots

    # ---------------------------------------------------------
    # PARTIE 2 ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¦ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â Extraction des annotations
    # ---------------------------------------------------------
    def extract_annotations(self):
        annotations = []

        # Tiers qu'on veut exclure (mouthing)
        MOUSHING_KEYWORDS = ["ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â£ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¾ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¦ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¾ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â£ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¦ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¦ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â£ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â¦ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¸", "mouji", "Mouji", "MOUJI", "ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¥ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚ÂÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â£ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¥ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¦ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¾ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¹"]

        for tier in self.root.findall(".//TIER"):
            tier_id = tier.attrib.get("TIER_ID", "UNKNOWN")

            # ---- FILTRE MOUSHING ----
            if any(key in tier_id for key in MOUSHING_KEYWORDS):
                continue  # On ignore ce tier

            ling_type = tier.attrib.get("LINGUISTIC_TYPE_REF", None)

            # ALIGNABLE_ANNOTATION
            for ann in tier.findall(".//ALIGNABLE_ANNOTATION"):
                ann_id = ann.attrib.get("ANNOTATION_ID")
                ts1 = ann.attrib.get("TIME_SLOT_REF1")
                ts2 = ann.attrib.get("TIME_SLOT_REF2")

                start = self.time_slots.get(ts1, None)
                end = self.time_slots.get(ts2, None)
                duration = end - start if (start is not None and end is not None) else None

                value_elem = ann.find("ANNOTATION_VALUE")
                value = "".join(value_elem.itertext()).strip() if value_elem is not None else ""

                annotations.append({
                    "file": self.filename,      # <-- AJOUT ICI
                    "id": ann_id,
                    "tier": tier_id,
                    "linguistic_type": ling_type,
                    "value": value,
                    "start": start,
                    "end": end,
                    "duration": duration
                })

        return annotations

    # ---------------------------------------------------------
    # Tri chronologique
    # ---------------------------------------------------------
    def sorted_by_time(self):
        anns = self.extract_annotations()
        return sorted(
            anns,
            key=lambda x: (x["start"] if x["start"] is not None else 10**12)
        )

# Aggregation des annotations

In [89]:
annotations=[]
for file in eaf_list:
   path = file

   reader = EAFReader(path)
   annotations =annotations+reader.sorted_by_time()

   #for ann in annotations:
      # print(ann)
annotations[10]

{'file': '1NS_11-12_Cur.eaf',
 'id': 'a648',
 'tier': 'NS_11_SH_40F-Gloss-jp_S',
 'linguistic_type': 'default-lt',
 'value': 'カレー/作る/方法/何/か/',
 'start': 3407,
 'end': 5012,
 'duration': 1605}

# Fusion Word/POS et export CSV

In [90]:
import csv

def extract_speaker_name(tier_name):
    """
    Extrait FO_05 ou FO_06 ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â  partir du nom du tier.
    Exemple :
        FO_05_FK_80F-Word-jp ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¾ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ FO_05
        FO_06_FK_70F-POS-jp  ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¾ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ FO_06
    """
    parts = tier_name.split("_")
    if len(parts) >= 2:
        return parts[0] + "_" + parts[1]
    return "UNKNOWN"


def build_csv_from_annotations(annotations, output_csv):
    """
    Fusion Word-jp ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â POS-jp
    SÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©paration par personne (speaker)
    Export vers CSV, incluant le nom du fichier source.
    """

    # speakers["FO_05"]["words"][(start,end)] = {...}
    # speakers["FO_05"]["pos"][(start,end)] = "ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¥ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚ÂÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚ÂÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¨ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¦ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¾"
    speakers = {}

    for ann in annotations:
        tier = ann["tier"]
        value = ann["value"]
        start = ann["start"]
        end = ann["end"]
        duration = ann["duration"]
        file = ann.get("file", "UNKNOWN")    # <-- IMPORTANT

        # ---- Extraction de FO_05 ou FO_06 ----
        speaker = extract_speaker_name(tier)

        if speaker not in speakers:
            speakers[speaker] = {"words": {}, "pos": {}}

        key = (start, end)

        # ---- Tiers Word ----
        if "Word-jp" in tier:
            speakers[speaker]["words"][key] = {
                "word": value,
                "start": start,
                "end": end,
                "duration": duration,
                "tier": tier,
                "speaker": speaker,
                "file": file               # <-- AJOUT
            }

        # ---- Tiers POS ----
        if "POS-jp" in tier:
            speakers[speaker]["pos"][key] = value

    # -----------------------------------------
    # Fusion Word ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â POS
    # -----------------------------------------
    fused_rows = []

    for speaker, data in speakers.items():
        words = data["words"]
        pos_tags = data["pos"]

        for key, w in words.items():
            p = pos_tags.get(key, "")  # POS si prÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€šÃ‚Â ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¾Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©sent

            fused_rows.append({
                "speaker": speaker,
                "file": w["file"],          # <-- AJOUT
                "word": w["word"],
                "pos": p,
                "start": w["start"],
                "end": w["end"],
                "duration": w["duration"],
                "tier": w["tier"]
            })

    # Tri temporel
    fused_rows = sorted(fused_rows, key=lambda x: x["start"])

    # -----------------------------------------
    # EXPORT CSV
    # -----------------------------------------
    with open(output_csv, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["speaker", "file", "word", "pos", "start", "end", "duration", "tier"])

        for row in fused_rows:
            writer.writerow([
                row["speaker"],
                row["file"],          # <-- AJOUT
                row["word"],
                row["pos"],
                row["start"],
                row["end"],
                row["duration"],
                row["tier"]
            ])

    print(f"[OK] CSV crÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©eÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¾ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ {output_csv}")

# Test de lecture d'un fichier

In [91]:
def build_csv_for_files(eaf_files, output_csv):
    annotations = []
    for path in eaf_files:
        reader = EAFReader(path)
        annotations = annotations + reader.sorted_by_time()

    build_csv_from_annotations(annotations, output_csv)

train_csv = 'data/jsl_tokens_train.csv'

build_csv_for_files(train, train_csv)

[OK] CSV crÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬ÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©eÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¾ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ data/jsl_tokens_train.csv

# Chemin du CSV

In [92]:
path_csv_train=r"C:\\Users\\Ewan\\Desktop\\Projet JAPON JSL\\python project\\data\\jsl_tokens_train.csv"

# Verification du CSV

In [93]:
tab=pd.read_csv(path_csv_train)
tab.columns = [str(c).strip().lower() for c in tab.columns]
if 'tier' not in tab.columns:
    raise ValueError('Missing tier in columns: ' + ','.join(tab.columns))
tab=tab.sort_values(['tier','start']).reset_index(drop=True)
tab

,speaker,file,word,pos,start,end,duration,tier
0,FO_05,FO_05-06_AniN.eaf,/たくさん,形容詞,0,683,683,FO_05_FK_80F-Word-jp
1,FO_05,FO_05-06_AniN.eaf,/いくつか,副詞,683,1268,585,FO_05_FK_80F-Word-jp
2,FO_05,FO_05-06_AniN.eaf,/まとめる,動詞,1268,1951,683,FO_05_FK_80F-Word-jp
3,FO_05,FO_05-06_AniN.eaf,/難しい,形容詞,1951,2274,323,FO_05_FK_80F-Word-jp
4,FO_05,FO_05-06_AniN.eaf,/まとめる,動詞,2274,3479,1205,FO_05_FK_80F-Word-jp
...,...,...,...,...,...,...,...,...
13950,TY_08,TY_07-08_Cur.eaf,反抗(口型:じぶんかって),動詞,570704,571855,1151,TY_08_TY_60M-Word-jp
13951,TY_08,TY_07-08_Cur.eaf,悪い(口型:だめ),名詞,571855,573306,1451,TY_08_TY_60M-Word-jp
13952,TY_08,TY_07-08_Cur.eaf,fal,感動詞,573707,574024,317,TY_08_TY_60M-Word-jp
13953,TY_08,TY_07-08_Cur.eaf,本当,名詞,574024,574591,567,TY_08_TY_60M-Word-jp
13954,TY_08,TY_07-08_Cur.eaf,本当,名詞,574591,575175,584,TY_08_TY_60M-Word-jp

In [94]:
import pandas as pd

df = pd.read_csv("data/jsl_tokens_train.csv")

lines = []
for tier, g in df.groupby("tier"):
    words = g.sort_values("start")["word"].astype(str).tolist()
    lines.append(f"[TIER] {tier}")
    lines.append("/".join(words))
    lines.append("")

with open("jsl_tokens_train_concat.txt", "w", encoding="utf-8") as f:
    f.write("".join(lines))
tab

,speaker,file,word,pos,start,end,duration,tier
0,FO_05,FO_05-06_AniN.eaf,/たくさん,形容詞,0,683,683,FO_05_FK_80F-Word-jp
1,FO_05,FO_05-06_AniN.eaf,/いくつか,副詞,683,1268,585,FO_05_FK_80F-Word-jp
2,FO_05,FO_05-06_AniN.eaf,/まとめる,動詞,1268,1951,683,FO_05_FK_80F-Word-jp
3,FO_05,FO_05-06_AniN.eaf,/難しい,形容詞,1951,2274,323,FO_05_FK_80F-Word-jp
4,FO_05,FO_05-06_AniN.eaf,/まとめる,動詞,2274,3479,1205,FO_05_FK_80F-Word-jp
...,...,...,...,...,...,...,...,...
13950,TY_08,TY_07-08_Cur.eaf,反抗(口型:じぶんかって),動詞,570704,571855,1151,TY_08_TY_60M-Word-jp
13951,TY_08,TY_07-08_Cur.eaf,悪い(口型:だめ),名詞,571855,573306,1451,TY_08_TY_60M-Word-jp
13952,TY_08,TY_07-08_Cur.eaf,fal,感動詞,573707,574024,317,TY_08_TY_60M-Word-jp
13953,TY_08,TY_07-08_Cur.eaf,本当,名詞,574024,574591,567,TY_08_TY_60M-Word-jp
13954,TY_08,TY_07-08_Cur.eaf,本当,名詞,574591,575175,584,TY_08_TY_60M-Word-jp

# Nettoyage des tokens

In [95]:
# Nettoyage: chevrons + split '+' + filtre segments bruyants
import re
import unicodedata

def _drop_angle_and_inside(text):
    """
    Supprime tout ce qui est entre < > (chevrons), de facon robuste.
    """
    text = str(text)
    if '>' in text and '<' not in text:
        return text.split('>', 1)[1]
    if '<' in text and '>' not in text:
        return text.split('<', 1)[0]
    if '>' in text and '<' in text and text.find('>') < text.find('<'):
        return text.split('>', 1)[1].split('<', 1)[0]
    text = re.sub(r'<[^>]*>', '', text)
    text = text.replace('>', '')
    return text


def _clean_segment(seg):
    s = str(seg).strip()
    s = unicodedata.normalize('NFKC', s)
    s = s.lower()
    # PT colon handling: keep locus-id, or convert to pt(...).
    if re.fullmatch(r"(?i)^pt[123]?:[lrfub]$", s):
        return s
    m = re.fullmatch(r"(?i)^pt([123]?):(.+)$", s)
    if m:
        suffix = m.group(2).strip()
        if not re.fullmatch(r"(?i)[lrfub]", suffix):
            prefix = f"pt{m.group(1)}" if m.group(1) else "pt"
            return f"{prefix}({suffix})"

    # PT glued tokens: ptX -> pt+X (forces split)
    m = re.fullmatch(r"(?i)^pt([123])?([\u4e00-\u9fff\u3041-\u3096\u30a1-\u30fa].+)$", s)
    if m:
        digit = m.group(1) or ""
        rest = m.group(2)
        return f"pt{digit}+{rest}"
    if not s:
        return ''
    if s.startswith('??'):
        return 'UNKNOWN'

    # --------------------------------------------------
    # 1) Normalisation ponctuation fullwidth
    # --------------------------------------------------
    s = s.replace('\uFF1A', ':').replace('\uFF1B', ';').replace('\uFF0F', '/')
    s = s.replace('\uFF0F', '/').replace('\uFF0B', '+')
    # --------------------------------------------------
    # 1b) If '>' or '<' is isolated: a>b -> b, a<b -> a
    # --------------------------------------------------
    if '>' in s and '<' not in s:
        s = s.split('>')[-1].strip()
    if '<' in s and '>' not in s:
        s = s.split('<')[0].strip()

    # --------------------------------------------------
    # 2) Normalisation CL / GES (toutes variantes -> cl: / ges:)
    # --------------------------------------------------
    s = re.sub(r'(?i)\bcl\s*[:;/]\s*', 'cl:', s)
    s = re.sub(r'(?i)\bges\s*[:;/]\s*', 'ges:', s)
    s = re.sub(r'(?i)\baw\s*[:;/]\s*', 'aw:', s)
    s = re.sub(r'(?i)\bD\s*[:;/]\s*', 'D:', s)

    # --------------------------------------------------
    # 3) Nettoyage canaux main (LH / RH)
    # --------------------------------------------------
    s = re.sub(r'(?i)(^|[^A-Za-z])(?:rh|lh|R|L)\s*[:]\s*', r'\1', s)
    s = re.sub(r'(?i)/[LR]H\(([^)]*)\)', r'\1', s)
    s = re.sub(r'(?i)/[LR]H\b', '', s)
    s = re.sub(r'(?i)\(\s*(?:rh|lh)\s*\)', '', s)
    s = re.sub(r'(?i)\b(?:rh|lh)\b', '', s)

    # --------------------------------------------------
    # 3b) Nettoyage x2/x3 etc (y compris ×2)
    # --------------------------------------------------
    s = re.sub(r'(?i)[x\u00D7]\s*\d+', '', s)

    # --------------------------------------------------
    # 3c) If 'A/pt(...)' or 'A+pt(...)': keep pt(...)
    #     If 'A/pt' or 'A+pt': assign A to pt(A)
    # --------------------------------------------------
    if (('/' in s) or ('+' in s)) and re.search(r'(?i)\bpt[123]?\b', s):
        parts = [p for p in re.split(r'[+/]', s) if p]
        pt_idx = next((i for i, p in enumerate(parts) if re.search(r'(?i)\bpt[123]?\b', p)), None)
        if pt_idx is not None:
            pt_part = parts[pt_idx].strip()
            if not re.search(r'(?i)\bpt[123]?\s*\([^)]*\)', pt_part):
                other = next((p.strip() for i, p in enumerate(parts) if i != pt_idx and p.strip()), '')
                if other:
                    s = f"pt({other})"
            else:
                m = re.search(r'(?i)\bpt[123]?\s*\([^)]*\)', pt_part)
                if m:
                    s = m.group(0)

    # --------------------------------------------------
    # 3d) UNKNOWN/un avec / ou + : unknown(A) si A est present
    # --------------------------------------------------
    if (('/' in s) or ('+' in s)) and re.search(r'(?i)\b(?:un|unknown)\b', s):
        parts = [p for p in re.split(r'[+/]', s) if p]
        unk_idx = next((i for i, p in enumerate(parts) if re.search(r'(?i)\b(?:un|unknown)\b', p)), None)
        if unk_idx is not None:
            unk_part = parts[unk_idx].strip()
            if not re.search(r'(?i)\b(?:un|unknown)\s*\([^)]*\)', unk_part):
                other = next((p.strip() for i, p in enumerate(parts) if i != unk_idx and p.strip()), '')
                if other:
                    return f"unknown({other})"
            return 'unknown'

    # --------------------------------------------------
    # 4) Slashs: enlever aux extremites, remplacer au milieu par '+'
    # --------------------------------------------------
    s = re.sub(r'^/+', '', s)
    s = re.sub(r'/+$', '', s)
    s = re.sub(r'/+', '+', s)

    # --------------------------------------------------
    # 4a) Si un '+' subsiste, nettoyer chaque segment separement
    # --------------------------------------------------
    if '+' in s:
        parts = [p for p in s.split('+') if p]
        pt_idx = next((i for i, p in enumerate(parts) if re.search(r'(?i)^pt[123]?\b', p.strip())), None)
        if pt_idx is not None:
            pt_part = parts[pt_idx].strip()
            if not re.search(r'(?i)^pt[123]?\s*\([^)]*\)', pt_part):
                other = next((p.strip() for i, p in enumerate(parts) if i != pt_idx and p.strip()), '')
                if other:
                    return f"pt({other})"
        keep_nod = any(p.strip().lower().startswith('pt') for p in parts)
        cleaned = []
        for p in parts:
            if keep_nod and p.strip().lower() == 'nod':
                cleaned.append('nod')
                continue
            cleaned.append(_clean_segment(p))
        cleaned = [c for c in cleaned if c]
        if 'UNKNOWN' in cleaned:
            return 'UNKNOWN'
        joined = '+'.join(cleaned)
        # Après NFKC, on préfère réparer les parenthèses ASCII
        if joined.count('(') > joined.count(')'):
            joined += ')' * (joined.count('(') - joined.count(')'))
        # (optionnel) si jamais il reste des fullwidth
        if joined.count('\uFF08') > joined.count('\uFF09'):
            joined += '\uFF09' * (joined.count('\uFF08') - joined.count('\uFF09'))
        return joined

    # --------------------------------------------------
    # 4b) Unknown: remplace tout segment "un" par UNKNOWN
    #     sauf si "un" est suivi d'une lettre ou d'un chiffre
    # --------------------------------------------------
    if re.search(r'(?i)(?<![A-Za-z0-9])un(?![A-Za-z0-9])', s):
        return 'UNKNOWN'

    # --------------------------------------------------
    # 5) Coupe locale sur marqueurs bruyants
    #    -> on garde ce qu'il y a AVANT
    #    -> MAIS on ne coupe PAS apres une ')'
    # --------------------------------------------------
    # --------------------------------------------------
    # 5) Nettoyage local (hold) + mouthing m:
    #     - enlever hold
    #     - supprimer le segment (m:...)
    # --------------------------------------------------
    s = re.sub(r'(?i)\(\s*hold\s*\)', '', s)
    s = re.sub(r'(?i)\bhold\b', '', s)
    s = re.sub(r'\(\s*m:[^)]*\)', '', s)

    # --------------------------------------------------
    # 5b) Enlever (rep) / (omit...) en gardant le reste
    # --------------------------------------------------
    s = re.sub(r'(?i)\(\s*rep\s*\d*\s*\)?', '', s)
    s = re.sub(r'(?i)\brep\s*\d+\b', '', s)
    s = re.sub(r'(?i)\b\d+\s*rep\b', '', s)
    s = re.sub(r'(?i)\brep\b', '', s)
    s = re.sub(r'(?i)\bqm\b', '', s)
    s = re.sub(r'(?i)\(\s*omit[^)]*\)', '', s)

    # --------------------------------------------------
    # 5b2) Normalisation des variantes pt / dw
    # --------------------------------------------------
    s = re.sub(r'(?i)\b(pt[123]?)\s*[cn]\b', r'\1', s)
    s = re.sub(r'(?i)\b(pt[123]?)\s*dw\b', r'\1(dw)', s)
    s = re.sub(r'(?i)\b(pt[123]?)\s*dw[:/].*', r'\1(dw)', s)
    s = re.sub(r'(?i)\b(pt[123]?)\s*:\s*(\d+)\b', r'\1(\2)', s)

    # --------------------------------------------------
    # 5c) Supprimer nod/qm + parentheses seules/orphelines
    # --------------------------------------------------
    if re.fullmatch(r'(?i)(?:nod|qm)', s):
        return ''
    s = re.sub(r'^\(+', '', s)
    s = re.sub(r'\)+$', '', s)
    s = s.strip()
    if re.fullmatch(r'[()\[\]]+', s):
        return ''
    if re.fullmatch(r'[\(\[]\s*[\)\]]', s):
        return ''
    if re.fullmatch(r'[\(\[]\s*[\]\)]', s):
        return ''

    # --------------------------------------------------
    # 5c) Supprimer les numeraux et parentheses seules
    # --------------------------------------------------
    if re.fullmatch(r'\d+\([^)]*\)', s):
        return ''
    if re.match(r'^\d', s):
        return ''
    if re.fullmatch(r'[()]+', s):
        return ''

    # --------------------------------------------------
    # 6) Coupe locale sur marqueurs bruyants
    #    -> on garde ce qu'il y a AVANT
    #    -> MAIS on ne coupe PAS apres une ')'
    # --------------------------------------------------
    CUT_PATTERNS = [
        r'(?i)\bcl:',
        r'(?i)\bges:',
        r'(?i)\baw:',
        r'(?i)\bD:',
        r'\u53E3\u578B:',
        r'(?i)\bfal\b',
        r'(?i)\bfal:',
        r'(?i)\bNMM\b',
        r'(?i)\brep2?\b',
    ]

    # zone autorisee pour la coupe : avant le premier ')'
    paren_end = s.find(')')
    search_zone = s if paren_end == -1 else s[:paren_end]

    for pat in CUT_PATTERNS:
        m = re.search(pat, search_zone)
        if m:
            s = s[:m.start()].strip()
            break

    if not s:
        return ''

    # --------------------------------------------------
    # 6) Deparenthesage FINAL si le token est EXACTEMENT "(X)"
    #    (et seulement si X est simple)
    # --------------------------------------------------
    m = re.fullmatch(r'\(([^()]+)\)', s)
    if m:
        inner = m.group(1).strip()
        if inner and ':' not in inner and ' ' not in inner:
            s = inner

    m = re.search(r'(?i)\bpt\s*\([^)]*\)', s)
    if m and '/' in s:
        s = m.group(0)
    # Final cleanup for empty/mismatched parentheses
    s = re.sub(r'\(\s*\)', '', s)
    s = re.sub(r'\[\s*\]', '', s)
    s = re.sub(r'\uFF08\s*\uFF09', '', s)
    if re.fullmatch(r'[\(\[]\s*[\)\]]', s):
        return ''
    if re.fullmatch(r'[\(\[]\s*[\]\)]', s):
        return ''
    if s.count('(') > s.count(')'):
        s = s + (')' * (s.count('(') - s.count(')')))
    if s.count('\uFF08') > s.count('\uFF09'):
        s = s + ('\uFF09' * (s.count('\uFF08') - s.count('\uFF09')))
    return s


def _smart_split_plus(text):
    s = str(text)
    parts = []
    buf = []
    paren = 0
    angle = 0
    for ch in s:
        if ch == '(':
            paren += 1
        elif ch == ')' and paren > 0:
            paren -= 1
        elif ch == '<':
            angle += 1
        elif ch == '>' and angle > 0:
            angle -= 1
        if ch == '+' and paren == 0 and angle == 0:
            parts.append(''.join(buf))
            buf = []
        else:
            buf.append(ch)
    parts.append(''.join(buf))
    return parts


# ======================================================
# PIPELINE COMPLET
# ======================================================

tab['word'] = tab['word'].apply(_drop_angle_and_inside)
tab['word'] = tab['word'].astype(str).str.replace('\uFF0B', '+')
tab['word'] = tab['word'].apply(_smart_split_plus)
tab = tab.explode('word').reset_index(drop=True)
tab['pos'] = tab['pos'].astype(str).apply(lambda x: unicodedata.normalize('NFKC', x))
tab = tab[tab['pos'].str.contains(r'(名詞|動詞|代名詞)', regex=True, na=False)]
tab['word'] = tab['word'].apply(_clean_segment)

# Securite finale
tab = tab[~tab['word'].astype(str).str.match(r'(?i)^(?:aw:|D:)$', na=False)]
tab = tab[tab['word'].astype(str).str.len().gt(0)]

C:\Users\Ewan\AppData\Local\Temp\ipykernel_24796\458279403.py:306: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  tab = tab[tab['pos'].str.contains(r'(名詞|動詞|代名詞)', regex=True, na=False)]

In [96]:
# Mini-tests PT normalization
examples = ["pt\uff12", "pt:f", "pt:\u606f\u5b50", "pt3:\u3072\u3088\u3053or...", "pt\u63b4\u3080", "A/pt"]
for ex in examples:
    cleaned = _clean_segment(ex)
    split = _smart_split_plus(cleaned)
    print(ex, '=>', split)

pt２ => ['pt2']
pt:f => ['pt:f']
pt:息子 => ['pt(息子)']
pt3:ひよこor... => ['pt3(ひよこor...)']
pt掴む => ['pt', '掴む']
A/pt => ['pt(a)']

In [97]:
tab

,speaker,file,word,pos,start,end,duration,tier
2,FO_05,FO_05-06_AniN.eaf,まとめる,動詞,1268,1951,683,FO_05_FK_80F-Word-jp
4,FO_05,FO_05-06_AniN.eaf,まとめる,動詞,2274,3479,1205,FO_05_FK_80F-Word-jp
5,FO_05,FO_05-06_Cur.eaf,料理,名詞,3260,3840,580,FO_05_FK_80F-Word-jp
7,FO_05,FO_05-06_AniN.eaf,テレビ,名詞,6229,6559,330,FO_05_FK_80F-Word-jp
8,FO_05,FO_05-06_AniN.eaf,pt3,代名詞,6559,6960,401,FO_05_FK_80F-Word-jp
...,...,...,...,...,...,...,...,...
14331,TY_08,TY_07-08_Cur.eaf,自分(stop),名詞,570453,570704,251,TY_08_TY_60M-Word-jp
14332,TY_08,TY_07-08_Cur.eaf,反抗(),動詞,570704,571855,1151,TY_08_TY_60M-Word-jp
14333,TY_08,TY_07-08_Cur.eaf,悪い(),名詞,571855,573306,1451,TY_08_TY_60M-Word-jp
14335,TY_08,TY_07-08_Cur.eaf,本当,名詞,574024,574591,567,TY_08_TY_60M-Word-jp
14336,TY_08,TY_07-08_Cur.eaf,本当,名詞,574591,575175,584,TY_08_TY_60M-Word-jp

# Segmentation et preparation des phrases

In [98]:
# Regroupe les mots en phrases par tier selon un seuil d'ecart (ms)
gap_ms = 500
tab = tab.sort_values(['tier', 'start']).reset_index(drop=True)
tab['start'] = pd.to_numeric(tab['start'], errors='coerce')
tab['end'] = pd.to_numeric(tab['end'], errors='coerce')
# Merge rows with same tier/start/end before sentence grouping
group_cols = ['tier', 'start', 'end']
agg = {
    'word': lambda s: '/'.join(s.astype(str)),
    'pos': lambda s: '/'.join(s.astype(str)),
}
for c in tab.columns:
    if c not in group_cols + ['word', 'pos']:
        agg[c] = 'first'
tab = (tab.sort_values(group_cols)
          .groupby(group_cols, as_index=False, sort=False)
          .agg(agg))
prev_end = tab.groupby('tier')['end'].shift(1)
prev_word = tab.groupby('tier')['word'].shift(1)
tab['gap'] = tab['start'] - prev_end
def _is_boundary_word_strong(value):
    s = str(value).strip().lower()
    markers = ("stop", "owari", "\u7d42\u308f\u308b", "\u7d42\u308f\u308a")
    return any(m in s for m in markers)
def _is_boundary_word_weak(value):
    s = str(value).strip().lower()
    return "?" in s
def _is_boundary_word_any(value):
    return _is_boundary_word_strong(value) or _is_boundary_word_weak(value)
tab['prev_boundary'] = prev_word.apply(_is_boundary_word_strong)
tab['prev_boundary_weak'] = prev_word.apply(_is_boundary_word_weak)
tab['separation'] = tab['prev_boundary'].astype(int)
tab['boundary_strength'] = tab['prev_boundary'].map({True: 2, False: 0})
tab.loc[~tab['prev_boundary'] & tab['prev_boundary_weak'], 'boundary_strength'] = 1
tab['new_sentence'] = tab['gap'].fillna(0).ge(gap_ms) | tab['prev_boundary'] | tab['prev_boundary_weak']
tab['sentence_id'] = tab.groupby('tier')['new_sentence'].cumsum()
# Retire les tokens boundary apres la segmentation
tab = tab[~tab['word'].apply(_is_boundary_word_strong)]
def _merge_fs_tokens(tokens, pos):
    merged_tokens = []
    merged_pos = []
    i = 0
    while i < len(tokens):
        t = tokens[i]
        if isinstance(t, str) and t.lower().startswith('fs:'):
            parts = []
            keep_pos = pos[i] if i < len(pos) else None
            while i < len(tokens) and isinstance(tokens[i], str) and tokens[i].lower().startswith('fs:'):
                parts.append(tokens[i][3:])
                i += 1
            merged = ''.join(parts)
            if merged:
                merged_tokens.append(merged)
                if pos:
                    merged_pos.append(keep_pos)
            continue
        merged_tokens.append(t)
        if pos:
            merged_pos.append(pos[i])
        i += 1
    return merged_tokens, merged_pos

phrases = (tab.groupby(['tier', 'sentence_id'])
           .agg(file=('file','first'), start=('start','min'), end=('end','max'),
                tokens=('word', list), pos=('pos', list),
                separation=('separation','max'), boundary_strength=('boundary_strength','max'))
           .reset_index())
phrases[['tokens', 'pos']] = phrases.apply(
    lambda r: pd.Series(_merge_fs_tokens(r['tokens'], r['pos'])), axis=1
)
def _clean_tokens_list(tokens):
    cleaned = []
    for t in tokens:
        c = _clean_segment(t)
        if not c:
            continue
        # Ultimate fallback: pt/xxx or pt+xxx -> pt(xxx)
        if (('/' in c) or ('+' in c)) and re.search(r'(?i)\bpt[123]?\b', c) and not re.search(r'(?i)\bpt[123]?\s*\([^)]*\)', c):
            parts = [p.strip() for p in re.split(r'[+/]', c) if p.strip()]
            pt_idx = next((i for i, p in enumerate(parts) if re.fullmatch(r'(?i)pt[123]?\b', p)), None)
            if pt_idx is not None:
                other = next((p for i, p in enumerate(parts) if i != pt_idx and p), '')
                if other:
                    c = f"pt({other})"
        if ('/' in c) or ('+' in c):
            m = re.search(r'(?i)\bpt[123]?\s*\([^)]*\)', c)
            if m:
                c = m.group(0)
        # Final pass: remove empty ()/[] left after filtering
        c = re.sub(r'[\(\uff08]\s*[\)\uff09]', '', c)
        c = re.sub(r'[\[\uff3b]\s*[\]\uff3d]', '', c)
        c = c.strip()
        if c and re.fullmatch(r'[\(\[]\s*[\)\]\(\[]?\s*[\)\]]?', c):
            continue
        if c:
            cleaned.append(c)
    return cleaned
phrases['tokens'] = phrases['tokens'].apply(_clean_tokens_list)
phrases = phrases.sort_values(['file', 'start', 'end']).reset_index(drop=True)
phrases

,tier,sentence_id,file,start,end,tokens,pos,separation,boundary_strength
0,FO_05_FK_80F-Word-jp,0,FO_05-06_AniN.eaf,1268,3840,"[まとめる, まとめる, 料理]","[動詞, 動詞, 名詞]",0,0
1,FO_05_FK_80F-Word-jp,1,FO_05-06_AniN.eaf,6229,18230,"[テレビ, pt3, テレビ, 見た, pt, 漫画, pt1, 食べる(カレー), pt3, pt1, カレー, 漫画, カレー, pt2, pt, pt1, pt2, 自分, pt2, カレー, 呼びかけ, カレー, いえいえ, pt1, みた, 答える, 相手を)待つ, pt3, 漫画, pt3, pt3]","[名詞, 代名詞, 名詞, 動詞, 代名詞, 名詞, 代名詞, 名詞, 代名詞, 代名詞, 名詞, 名詞, 名詞, 代名詞, 代名詞, 代名詞, 代名詞, 名詞, 代名詞, 名詞, 感動詞, 名詞, 感動詞, 代名詞, 動詞, 動詞, 動詞, 代名詞, 名詞, 代名詞, 代名詞]",0,0
2,FO_05_FK_80F-Word-jp,2,FO_05-06_AniN.eaf,18793,20306,"[pt3, pt3, 何]","[代名詞, 代名詞, 名詞]",0,0
3,FO_05_FK_80F-Word-jp,3,FO_05-06_AniN.eaf,21240,33170,"[猫, pt2, カレー, pt2, 流, 猫, 真似る, 違う, 犬, どっち, わからない, 絵, 犬, 見る, 犬, 猫, みる, 絵, 耳, 呼びかけ, 耳, ある, 猫]","[名詞, 代名詞, 名詞, 代名詞, 名詞, 名詞, 動詞, 助動詞, 名詞, 名詞, 動詞, 名詞, 名詞, 動詞, 名詞, 名詞, 動詞, 名詞, 名詞, 代名詞, 名詞, 動詞, 名詞]",0,0
4,FO_05_FK_80F-Word-jp,4,FO_05-06_AniN.eaf,34178,35879,"[絵, 動き, 真似る]","[名詞, 名詞, 動詞]",0,0
...,...,...,...,...,...,...,...,...,...
2044,TY_08_TY_60M-Word-jp,117,TY_07-08_Cur.eaf,555972,557273,"[pt3, 運]","[代名詞, 名詞]",0,0
2045,TY_08_TY_60M-Word-jp,118,TY_07-08_Cur.eaf,564864,570453,"[本当, pt3, pt3(呼びかけ), 呼びかけ, pt3, unknown, pt3(前出の担当者), 怒る, pt3(前での担当者), 責任, pt2]","[名詞, 代名詞, 代名詞, 感動詞, 代名詞, 名詞, 代名詞, 動詞, 代名詞, 名詞, 名詞]",0,0
2046,TY_07_TY_60M-Word-jp,89,TY_07-08_Cur.eaf,569269,570103,[はらう(意味:いや)],[感動詞],0,0
2047,TY_08_TY_60M-Word-jp,119,TY_07-08_Cur.eaf,570704,573306,"[反抗, 悪い]","[動詞, 名詞]",1,2
2048,TY_08_TY_60M-Word-jp,120,TY_07-08_Cur.eaf,574024,575175,"[本当, 本当]","[名詞, 名詞]",0,0

# Construction des tokens JSON

In [99]:
import unicodedata

def _token_pos_json(tokens, pos, separation=None):

    merged = []

    for t, p in zip(tokens, pos):

        t_str = str(t)

        t_str = unicodedata.normalize('NFKC', t_str)

        mods = [m.strip() for m in re.findall(r'\(([^()]*)\)', t_str) if m.strip()]

        word = re.sub(r'\([^()]*\)', '', t_str).strip()

        tok = {"word": word, "pos": p, "mods_raw": mods, "modifier": {}}

        wnorm = unicodedata.normalize("NFKC", str(word)).strip().lower()

        if wnorm.startswith("pt"):

            tok["modifier"]["is_pt"] = True

            if mods:

                tok["modifier"]["pt_ref"] = mods[0]

        merged.append(tok)

    if merged:

        last = merged[-1]

        last["modifier"]["end_token"] = True

    return merged


phrases_json = phrases.drop(columns=['pos']).copy()

phrases_json['tokens'] = phrases.apply(

    lambda r: _token_pos_json(r['tokens'], r['pos'], r.get('separation', None)), axis=1

)

phrases_json

,tier,sentence_id,file,start,end,tokens,separation,boundary_strength
0,FO_05_FK_80F-Word-jp,0,FO_05-06_AniN.eaf,1268,3840,"[{'word': 'まとめる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'まとめる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '料理', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]",0,0
1,FO_05_FK_80F-Word-jp,1,FO_05-06_AniN.eaf,6229,18230,"[{'word': 'テレビ', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'テレビ', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '見た', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '漫画', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '食べる', 'pos': '名詞', 'mods_raw': ['カレー'], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '漫画', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt2', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt2', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '自分', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt2', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '呼びかけ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'いえいえ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'みた', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '答える', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '相手を)待つ', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '漫画', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'end_token': True}}]",0,0
2,FO_05_FK_80F-Word-jp,2,FO_05-06_AniN.eaf,18793,20306,"[{'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '何', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]",0,0
3,FO_05_FK_80F-Word-jp,3,FO_05-06_AniN.eaf,21240,33170,"[{'word': '猫', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt2', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt2', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '流', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '猫', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '真似る', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '違う', 'pos': '助動詞', 'mods_raw': [], 'modifier': {}}, {'word': '犬', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'どっち', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'わからない', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '絵', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '犬', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '見る', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '犬', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '猫', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'みる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '絵', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '耳', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '呼びかけ', 'pos': '代名詞', 'mods_raw': [], 'modifier': {}}, {'word': '耳', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'ある', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '猫', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]",0,0
4,FO_05_FK_80F-Word-jp,4,FO_05-06_AniN.eaf,34178,35879,"[{'word': '絵', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '動き', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '真似る', 'pos': '動詞', 'mods_raw': [], 'modifier': {'end_token': True}}]",0,0
...,...,...,...,...,...,...,...,...
2044,TY_08_TY_60M-Word-jp,117,TY_07-08_Cur.eaf,555972,557273,"[{'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '運', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]",0,0
2045,TY_08_TY_60M-Word-jp,118,TY_07-08_Cur.eaf,564864,570453,"[{'word': '本当', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': ['呼びかけ'], 'modifier': {'is_pt': True, 'pt_ref': '呼びかけ'}}, {'word': '呼びかけ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'unknown', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': ['前出の担当者'], 'modifier': {'is_pt': True, 'pt_ref': '前出の担当者'}}, {'word': '怒る', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': ['前での担当者'], 'modifier': {'is_pt': True, 'pt_ref': '前での担当者'}}, {'word': '責任', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt2', 'pos': '名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'end_token': True}}]",0,0
2046,TY_07_TY_60M-Word-jp,89,TY_07-08_Cur.eaf,569269,570103,"[{'word': 'はらう', 'pos': '感動詞', 'mods_raw': ['意味:いや'], 'modifier': {'end_token': True}}]",0,0
2047,TY_08_TY_60M-Word-jp,119,TY_07-08_Cur.eaf,570704,573306,"[{'word': '反抗', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '悪い', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]",1,2
2048,TY_08_TY_60M-Word-jp,120,TY_07-08_Cur.eaf,574024,575175,"[{'word': '本当', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '本当', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]",0,0

# Regles heuristiques

In [100]:
from token_utils import (
    is_unknown,
    is_verb,
    is_noun,
    is_adj,
    is_verb_token,
    is_boundary,
    is_pt,
    pt_key,
    classify_verb_valence,
    apply_R29_merge_unknown_runs,
    apply_R24R7_merge_repetitions,
    apply_rule_to_corpus,
)

example_tokens = [
    {"word": "UNKNOWN", "pos": "unknown", "modifier": {}},
    {"word": "?", "pos": "?"},
    {"word": "DOG", "pos": "noun", "modifier": {}},
    {"word": "unknown", "pos": "noun"},
    {"word": "pt1", "pos": "pron", "modifier": {}},
    {"word": "UNKNOWN", "pos": "unknown"},
    {"word": "UNKNOWN", "pos": "unknown"},
]
print("before:", example_tokens)
print("after:", apply_R29_merge_unknown_runs(example_tokens))

example_reps = [
    {"word": "DOG", "pos": "noun", "modifier": {}},
    {"word": "dog", "pos": "noun"},
    {"word": "???", "pos": "??", "modifier": {}},
    {"word": "???", "pos": "??"},
    {"word": "pt2", "pos": "pron", "modifier": {}},
    {"word": "pt2", "pos": "pron"},
    {"word": "???", "pos": "??", "modifier": {}},
    {"word": "???", "pos": "??"},
]
print("before reps:", example_reps)
print("after reps:", apply_R24R7_merge_repetitions(example_reps))

valence_dict = {"???": "transitive"}
print("is_verb_token(???, ??):", is_verb_token("???", "??", valence_dict))

before: [{'word': 'UNKNOWN', 'pos': 'unknown', 'modifier': {}}, {'word': '?', 'pos': '?'}, {'word': 'DOG', 'pos': 'noun', 'modifier': {}}, {'word': 'unknown', 'pos': 'noun'}, {'word': 'pt1', 'pos': 'pron', 'modifier': {}}, {'word': 'UNKNOWN', 'pos': 'unknown'}, {'word': 'UNKNOWN', 'pos': 'unknown'}]
after: [{'word': 'UNKNOWN', 'pos': 'unknown', 'modifier': {'sequenced': 2}}, {'word': 'DOG', 'pos': 'noun', 'modifier': {}}, {'word': 'UNKNOWN', 'pos': 'unknown', 'modifier': {'sequenced': 1}}, {'word': 'pt1', 'pos': 'pron', 'modifier': {}}, {'word': 'UNKNOWN', 'pos': 'unknown', 'modifier': {'sequenced': 2}}]
before reps: [{'word': 'DOG', 'pos': 'noun', 'modifier': {}}, {'word': 'dog', 'pos': 'noun'}, {'word': '???', 'pos': '??', 'modifier': {}}, {'word': '???', 'pos': '??'}, {'word': 'pt2', 'pos': 'pron', 'modifier': {}}, {'word': 'pt2', 'pos': 'pron'}, {'word': '???', 'pos': '??', 'modifier': {}}, {'word': '???', 'pos': '??'}]
after reps: [{'word': 'DOG', 'pos': 'noun', 'modifier': {'iterative': 2}}, {'word': '???', 'pos': '??', 'modifier': {'iterative': 2}}, {'word': 'pt2', 'pos': 'pron', 'modifier': {'pt_emphasis': 2}}, {'word': '???', 'pos': '??', 'modifier': {'iterative': 2}}]
is_verb_token(???, ??): True

In [101]:
import copy
from IPython.display import display

pd.set_option('display.max_colwidth', None)

before_tokens = phrases_json['tokens'].apply(copy.deepcopy)

after_tokens = apply_rule_to_corpus(
    copy.deepcopy(phrases_json['tokens']), apply_R29_merge_unknown_runs
)
after_tokens = apply_rule_to_corpus(
    after_tokens, apply_R24R7_merge_repetitions
)

seq_count = sum(
    1 for toks in after_tokens for t in toks if (t.get('modifier') or {}).get('sequenced') is not None
)
iter_count = sum(
    1 for toks in after_tokens for t in toks if (t.get('modifier') or {}).get('iterative') is not None
)
print('sequenced tokens:', int(seq_count))
print('iterative tokens:', int(iter_count))

changed_idx = [i for i, (b, a) in enumerate(zip(before_tokens, after_tokens)) if b != a]
print('changed phrases:', len(changed_idx))
if changed_idx:
    diff_rows = pd.DataFrame({
        'idx': changed_idx,
        'before': [before_tokens[i] for i in changed_idx],
        'after': [after_tokens[i] for i in changed_idx],
    })
    diff_rows['before_words'] = diff_rows['before'].apply(
        lambda toks: ' '.join(str(t.get('word', '')) for t in toks)
    )
    diff_rows['after_words'] = diff_rows['after'].apply(
        lambda toks: ' '.join(str(t.get('word', '')) for t in toks)
    )
    display(diff_rows[['idx', 'before_words', 'after_words', 'before', 'after']].head(20).reset_index(drop=True))

sequenced tokens: 185
iterative tokens: 222
changed phrases: 423

,idx,before_words,after_words,before,after
0,0,まとめる まとめる 料理,まとめる 料理,"[{'word': 'まとめる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'まとめる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '料理', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]","[{'word': 'まとめる', 'pos': '動詞', 'mods_raw': [], 'modifier': {'iterative': 2}}, {'word': '料理', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]"
1,1,テレビ pt3 テレビ 見た pt 漫画 pt1 食べる pt3 pt1 カレー 漫画 カレー pt2 pt pt1 pt2 自分 pt2 カレー 呼びかけ カレー いえいえ pt1 みた 答える 相手を)待つ pt3 漫画 pt3 pt3,テレビ pt3 テレビ 見た pt 漫画 pt1 食べる pt3 pt1 カレー 漫画 カレー pt2 pt pt1 pt2 自分 pt2 カレー 呼びかけ カレー いえいえ pt1 みた 答える 相手を)待つ pt3 漫画 pt3,"[{'word': 'テレビ', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'テレビ', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '見た', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '漫画', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '食べる', 'pos': '名詞', 'mods_raw': ['カレー'], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '漫画', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt2', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt2', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '自分', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt2', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '呼びかけ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'いえいえ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'みた', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '答える', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '相手を)待つ', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '漫画', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'end_token': True}}]","[{'word': 'テレビ', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'テレビ', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '見た', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '漫画', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '食べる', 'pos': '名詞', 'mods_raw': ['カレー'], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '漫画', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt2', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt2', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '自分', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt2', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '呼びかけ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'いえいえ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'みた', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '答える', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '相手を)待つ', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '漫画', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'pt_emphasis': 2}}]"
2,2,pt3 pt3 何,pt3 何,"[{'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '何', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]","[{'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'pt_emphasis': 2}}, {'word': '何', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]"
3,6,動く 動き回る おかあさん 困る 違う どこ unknown 困る,動く 動き回る おかあさん 困る 違う どこ UNKNOWN 困る,"[{'word': '動く', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '動き回る', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'おかあさん', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '困る', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '違う', 'pos': '感動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'どこ', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'unknown', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '困る', 'pos': '動詞', 'mods_raw': [], 'modifier': {'end_token': True}}]","[{'word': '動く', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '動き回る', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'おかあさん', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '困る', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '違う', 'pos': '感動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'どこ', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'UNKNOWN', 'pos': 'unknown', 'mods_raw': [], 'modifier': {'sequenced': 1}}, {'word': '困る', 'pos': '動詞', 'mods_raw': [], 'modifier': {'end_token': True}}]"
4,7,いえいえ 見えない 向こう にげる unknown,いえいえ 見えない 向こう にげる UNKNOWN,"[{'word': 'いえいえ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {}}, {'word': '見えない', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '向こう', 'pos': '代名詞', 'mods_raw': ['雨どいの奥'], 'modifier': {}}, {'word': 'にげる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'unknown', 'pos': '動詞', 'mods_raw': [], 'modifier': {'end_token': True}}]","[{'word': 'いえいえ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {}}, {'word': '見えない', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '向こう', 'pos': '代名詞', 'mods_raw': ['雨どいの奥'], 'modifier': {}}, {'word': 'にげる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'UNKNOWN', 'pos': 'unknown', 'mods_raw': [], 'modifier': {'end_token': True, 'sequenced': 1}}]"
5,8,unknown,UNKNOWN,"[{'word': 'unknown', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]","[{'word': 'UNKNOWN', 'pos': 'unknown', 'mods_raw': [], 'modifier': {'end_token': True, 'sequenced': 1}}]"
6,25,unknown,UNKNOWN,"[{'word': 'unknown', 'pos': '動詞', 'mods_raw': [], 'modifier': {'end_token': True}}]","[{'word': 'UNKNOWN', 'pos': 'unknown', 'mods_raw': [], 'modifier': {'end_token': True, 'sequenced': 1}}]"
7,40,料理 料理 まとめて pt1 まとめて 好き 構わない pt1 カレー カレー カレー カレー みる カレー ない pt1 できない,料理 まとめて pt1 まとめて 好き 構わない pt1 カレー みる カレー ない pt1 できない,"[{'word': '料理', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '料理', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'まとめて', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'まとめて', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '好き', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '構わない', 'pos': '助動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'みる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'ない', 'pos': '助動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'できない', 'pos': '動詞', 'mods_raw': [], 'modifier': {'end_token': True}}]","[{'word': '料理', 'pos': '名詞', 'mods_raw': [], 'modifier': {'iterative': 2}}, {'word': 'まとめて', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'まとめて', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '好き', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '構わない', 'pos': '助動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {'iterative': 4}}, {'word': 'みる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'ない', 'pos': '助動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'できない', 'pos': '動詞', 'mods_raw': [], 'modifier': {'end_token': True}}]"
8,42,pt カレー 今 pt1 pt1 家,pt カレー 今 pt1 家,"[{'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '今', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '家', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]","[{'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '今', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'pt_emphasis': 2}}, {'word': '家', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]"
9,49,切る 置く pt じゃがいも じゃがいも 玉ねぎ,切る 置く pt じゃがいも 玉ねぎ,"[{'word': '切る', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '置く', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'じゃがいも', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'じゃがいも', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '玉ねぎ', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]","[{'word': '切る', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '置く', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'じゃがいも', 'pos': '名詞', 'mods_raw': [], 'modifier': {'iterative': 2}}, {'word': '玉ねぎ', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]"
10,52,pt pt,pt,"[{'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'end_token': True}}]","[{'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'pt_emphasis': 2}}]"
11,64,違う unknown pt カレー カレー る pt,違う UNKNOWN pt カレー る pt,"[{'word': '違う', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'unknown', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'る', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'end_token': True}}]","[{'word': '違う', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'UNKNOWN', 'pos': 'unknown', 'mods_raw': [], 'modifier': {'sequenced': 1}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {'iterative': 2}}, {'word': 'る', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'end_token': True}}]"
12,67,unknown 炒める 残り 表面 置く 水 足す,UNKNOWN 炒める 残り 表面 置く 水 足す,"[{'word': 'unknown', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '炒める', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '残り', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '表面', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '置く', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '水', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '足す', 'pos': '動詞', 'mods_raw': [], 'modifier': {'end_token': True}}]","[{'word': 'UNKNOWN', 'pos': 'unknown', 'mods_raw': [], 'modifier': {'sequenced': 1}}, {'word': '炒める', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '残り', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '表面', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '置く', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '水', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '足す', 'pos': '動詞', 'mods_raw': [], 'modifier': {'end_token': True}}]"
13,69,ガス 止める 置く カレー れ 入れる 入れる かき混ぜる,ガス 止める 置く カレー れ 入れる かき混ぜる,"[{'word': 'ガス', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '止める', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '置く', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'れ', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '入れる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '入れる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'かき混ぜる', 'pos': '動詞', 'mods_raw': [], 'modifier': {'end_token': True}}]","[{'word': 'ガス', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '止める', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '置く', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'れ', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '入れる', 'pos': '動詞', 'mods_raw': [], 'modifier': {'iterative': 2}}, {'word': 'かき混ぜる', 'pos': '動詞', 'mods_raw': [], 'modifier': {'end_token': True}}]"
14,74,pt2 pt2 流れ,pt2 流れ,"[{'word': 'pt2', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt2', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '流れ', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]","[{'word': 'pt2', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'pt_emphasis': 2}}, {'word': '流れ', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]"
15,88,pt ある わかる 脂肪 pt pt,pt ある わかる 脂肪 pt,"[{'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'ある', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'わかる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '脂肪', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'end_token': True}}]","[{'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'ある', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'わかる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '脂肪', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'pt_emphasis': 2}}]"
16,95,pt3 カレー 油 かける 入れる 炒める 炒める 炒める pt,pt3 カレー 油 かける 入れる 炒める pt,"[{'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '油', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'かける', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '入れる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '炒める', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '炒める', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '炒める', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'end_token': True}}]","[{'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '油', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'かける', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '入れる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '炒める', 'pos': '動詞', 'mods_raw': [], 'modifier': {'iterative': 3}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'end_token': True}}]"
17,96,玉ねぎ 入れる 玉ねぎ 入れる 炒める 変わる 人参 入れる じゃがいも 入れる 入れる 煮る pt3 水 ある 水,玉ねぎ 入れる 玉ねぎ 入れる 炒める 変わる 人参 入れる じゃがいも 入れる 煮る pt3 水 ある 水,"[{'word': '玉ねぎ', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '入れる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '玉ねぎ', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '入れる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '炒める', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '変わる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '人参', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '入れる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'じゃがいも', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '入れる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '入れる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '煮る', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '水', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'ある', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '水', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]","[{'word': '玉ねぎ', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '入れる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '玉ねぎ', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '入れる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '炒める', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '変わる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '人参', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '入れる', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'じゃがいも', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '入れる', 'pos': '動詞', 'mods_raw': [], 'modifier': {'iterative': 2}}, {'word': '煮る', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '水', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'ある', 'pos': '動詞', 'mods_raw': [], 'modifier': {}}, {'word': '水', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]"
18,97,同じ 同じ,同じ,"[{'word': '同じ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {}}, {'word': '同じ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {'end_token': True}}]","[{'word': '同じ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {'iterative': 2}}]"
19,106,pt 同じ 同じ,pt 同じ,"[{'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '同じ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {}}, {'word': '同じ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {'end_token': True}}]","[{'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '同じ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {'iterative': 2}}]"

In [102]:
import json

# Applique les fusions au corpus principal
phrases_json['tokens'] = after_tokens
phrases['tokens'] = after_tokens
phrases['pos'] = phrases_json['tokens'].apply(lambda toks: [t.get('pos') for t in toks])

# Sanity checks avant export
def _has_adjacent_duplicates(toks):
    words = [t.get('word') for t in toks]
    return any(words[i] == words[i-1] for i in range(1, len(words)))

dup_flags = phrases_json['tokens'].apply(_has_adjacent_duplicates)
pct_phrases_with_consecutive_duplicates = round(100 * dup_flags.mean(), 2) if len(dup_flags) else 0
count_iterative = sum(
    1 for toks in phrases_json['tokens'] for t in toks if (t.get('modifier') or {}).get('iterative') is not None
)
count_pt_emphasis = sum(
    1 for toks in phrases_json['tokens'] for t in toks if (t.get('modifier') or {}).get('pt_emphasis') is not None
)
count_boundary_emphasis = sum(
    1 for toks in phrases_json['tokens'] for t in toks if (t.get('modifier') or {}).get('boundary_emphasis') is not None
)
rows_len_mismatch = sum(
    1 for toks in phrases_json['tokens'] if len(toks) != len([t.get('pos') for t in toks])
)

print('pct_phrases_with_consecutive_duplicates:', pct_phrases_with_consecutive_duplicates)
print('count_iterative:', int(count_iterative))
print('count_pt_emphasis:', int(count_pt_emphasis))
print('count_boundary_emphasis:', int(count_boundary_emphasis))
print('rows_len_mismatch:', int(rows_len_mismatch))

# Export CSV final (tokens fusionnes)
export_df = phrases.copy()
export_df['tokens_json'] = phrases_json['tokens'].apply(lambda toks: json.dumps(toks, ensure_ascii=False))
export_df['tokens'] = phrases_json['tokens'].apply(lambda toks: [t.get('word') for t in toks])
export_df['pos'] = phrases_json['tokens'].apply(lambda toks: [t.get('pos') for t in toks])
export_df.to_csv('data/test2.csv', index=False, encoding='utf-8')

pct_phrases_with_consecutive_duplicates: 0.0
count_iterative: 222
count_pt_emphasis: 144
count_boundary_emphasis: 0
rows_len_mismatch: 0

# Valence des verbes
Ajoute la valence aux verbes via Jamdict.

# Valence des verbes

In [103]:
def annotate_verb_valence(tokens):
    for t in tokens:
        if not is_verb(t):
            continue
        lemma = t.get('lemma') or t.get('word')
        valence = classify_verb_valence(lemma)
        modifier = t.get('modifier') or {}
        modifier['valence'] = valence
        t['modifier'] = modifier
    return tokens

phrases_json['tokens'] = phrases_json['tokens'].apply(annotate_verb_valence)

In [104]:
verb_counts = phrases_json["tokens"].apply(lambda toks: sum(1 for t in toks if is_verb(t)))
print("phrases avec verbe:", (verb_counts > 0).sum())
print("phrases sans verbe:", (verb_counts == 0).sum())

no_lemma = phrases_json["tokens"].apply(
    lambda toks: [t for t in toks if is_verb(t) and (t.get("lemma") is None)]
).explode().dropna()
print("verbes sans lemma:", len(no_lemma))
display(no_lemma.head(10))

phrases avec verbe: 1098
phrases sans verbe: 951
verbes sans lemma: 2269

0    {'word': 'まとめる', 'pos': '動詞', 'mods_raw': [], 'modifier': {'iterative': 2, 'valence': 'transitive'}}
1                         {'word': '見た', 'pos': '動詞', 'mods_raw': [], 'modifier': {'valence': 'unknown'}}
1                         {'word': 'みた', 'pos': '動詞', 'mods_raw': [], 'modifier': {'valence': 'unknown'}}
1                   {'word': '答える', 'pos': '動詞', 'mods_raw': [], 'modifier': {'valence': 'intransitive'}}
1                     {'word': '相手を)待つ', 'pos': '動詞', 'mods_raw': [], 'modifier': {'valence': 'unknown'}}
3                     {'word': '真似る', 'pos': '動詞', 'mods_raw': [], 'modifier': {'valence': 'transitive'}}
3                      {'word': 'わからない', 'pos': '動詞', 'mods_raw': [], 'modifier': {'valence': 'unknown'}}
3                      {'word': '見る', 'pos': '動詞', 'mods_raw': [], 'modifier': {'valence': 'transitive'}}
3                      {'word': 'みる', 'pos': '動詞', 'mods_raw': [], 'modifier': {'valence': 'transitive'}}
3                    {'word': 'ある', 'pos': '動詞', 'mods_raw': [], 'modifier': {'valence': 'intransitive'}}
Name: tokens, dtype: object

In [105]:
from segmentation import segment_clauses
import pandas as pd

def _explode_clauses(row):
    clauses = segment_clauses(row["tokens"])
    base = row.to_dict()
    out = []
    for idx, clause in enumerate(clauses):
        r = dict(base)
        r["clause_index"] = idx
        r["tokens"] = clause["tokens"]
        r["split"] = clause["split"]
        r["boundary_seen"] = clause["boundary_seen"]
        r["clause_flags"] = clause.get("clause_flags")
        out.append(r)
    return out

clauses_rows = []
for _, row in phrases_json.iterrows():
    clauses_rows.extend(_explode_clauses(row))

clauses_json = pd.DataFrame(clauses_rows)
clauses_json

,tier,sentence_id,file,start,end,tokens,separation,boundary_strength,clause_index,split,boundary_seen,clause_flags
0,FO_05_FK_80F-Word-jp,0,FO_05-06_AniN.eaf,1268,3840,"[{'word': 'まとめる', 'pos': '動詞', 'mods_raw': [], 'modifier': {'iterative': 2, 'valence': 'transitive'}}, {'word': '料理', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]",0,0,0,None,False,{'verb_valences': ['transitive']}
1,FO_05_FK_80F-Word-jp,1,FO_05-06_AniN.eaf,6229,18230,"[{'word': 'テレビ', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'テレビ', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '見た', 'pos': '動詞', 'mods_raw': [], 'modifier': {'valence': 'unknown'}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '漫画', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '食べる', 'pos': '名詞', 'mods_raw': ['カレー'], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '漫画', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt2', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'pt2', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '自分', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt2', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': '呼びかけ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'カレー', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'いえいえ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt1', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}]",0,0,0,"{'reason': 'S_PAT', 'conf': 0.75, 'at': 24, 'flags': {'patient_consumed': True, 'has_new_object_candidate': False, 'splits_so_far': 0, 'conf_decay': 0.0}}",False,"{'verb_valences': ['unknown', 'unknown']}"
2,FO_05_FK_80F-Word-jp,1,FO_05-06_AniN.eaf,6229,18230,"[{'word': 'みた', 'pos': '動詞', 'mods_raw': [], 'modifier': {'valence': 'unknown'}}, {'word': '答える', 'pos': '動詞', 'mods_raw': [], 'modifier': {'valence': 'intransitive'}}]",0,0,1,"{'reason': 'S_VERB', 'conf': 0.7999999999999999, 'at': 26, 'flags': {'verb_count_in_clause': 3, 'splits_so_far': 1, 'conf_decay': 0.05}}",False,"{'verb_valences': ['intransitive', 'unknown']}"
3,FO_05_FK_80F-Word-jp,1,FO_05-06_AniN.eaf,6229,18230,"[{'word': '相手を)待つ', 'pos': '動詞', 'mods_raw': [], 'modifier': {'valence': 'unknown'}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '漫画', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'pt_emphasis': 2}}]",0,0,2,None,False,{}
4,FO_05_FK_80F-Word-jp,2,FO_05-06_AniN.eaf,18793,20306,"[{'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'pt_emphasis': 2}}, {'word': '何', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]",0,0,0,None,False,{}
...,...,...,...,...,...,...,...,...,...,...,...,...
2792,TY_08_TY_60M-Word-jp,117,TY_07-08_Cur.eaf,555972,557273,"[{'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': '運', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]",0,0,0,None,False,{}
2793,TY_08_TY_60M-Word-jp,118,TY_07-08_Cur.eaf,564864,570453,"[{'word': '本当', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'pt_emphasis': 2}}, {'word': '呼びかけ', 'pos': '感動詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': [], 'modifier': {'is_pt': True}}, {'word': 'UNKNOWN', 'pos': 'unknown', 'mods_raw': [], 'modifier': {'sequenced': 1}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': ['前出の担当者'], 'modifier': {'is_pt': True, 'pt_ref': '前出の担当者'}}, {'word': '怒る', 'pos': '動詞', 'mods_raw': [], 'modifier': {'valence': 'ambitransitive'}}, {'word': 'pt3', 'pos': '代名詞', 'mods_raw': ['前での担当者'], 'modifier': {'is_pt': True, 'pt_ref': '前での担当者'}}, {'word': '責任', 'pos': '名詞', 'mods_raw': [], 'modifier': {}}, {'word': 'pt2', 'pos': '名詞', 'mods_raw': [], 'modifier': {'is_pt': True, 'end_token': True}}]",0,0,0,None,False,{'verb_valences': ['ambitransitive']}
2794,TY_07_TY_60M-Word-jp,89,TY_07-08_Cur.eaf,569269,570103,"[{'word': 'はらう', 'pos': '感動詞', 'mods_raw': ['意味:いや'], 'modifier': {'end_token': True}}]",0,0,0,None,False,{}
2795,TY_08_TY_60M-Word-jp,119,TY_07-08_Cur.eaf,570704,573306,"[{'word': '反抗', 'pos': '動詞', 'mods_raw': [], 'modifier': {'valence': 'unknown'}}, {'word': '悪い', 'pos': '名詞', 'mods_raw': [], 'modifier': {'end_token': True}}]",1,2,0,None,False,{'verb_valences': ['unknown']}
2796,TY_08_TY_60M-Word-jp,120,TY_07-08_Cur.eaf,574024,575175,"[{'word': '本当', 'pos': '名詞', 'mods_raw': [], 'modifier': {'iterative': 2}}]",0,0,0,None,False,{}

In [106]:
import importlib, token_utils, roles_parser
print("token_utils:", token_utils.__file__)
print("roles_parser:", roles_parser.__file__)
print("pt_key(pt3):", token_utils.pt_key({"word":"pt3","pos":"代名詞"}))

importlib.reload(token_utils)
importlib.reload(roles_parser)

token_utils: c:\Users\Ewan\Desktop\Projet JAPON JSL\python project\token_utils.py
roles_parser: c:\Users\Ewan\Desktop\Projet JAPON JSL\python project\roles_parser.py
pt_key(pt3): pt3

In [107]:
import ast
import json
import pandas as pd
from roles_parser import parse_all_clauses

def _parse_tokens(value):
    if value is None or str(value).strip() == "":
        return []
    txt = str(value).strip()
    try:
        return json.loads(txt)
    except Exception:
        try:
            return ast.literal_eval(txt)
        except Exception:
            return []

def _parse_dict(value):
    if value is None or str(value).strip() == "":
        return None
    txt = str(value).strip()
    try:
        return json.loads(txt)
    except Exception:
        try:
            return ast.literal_eval(txt)
        except Exception:
            return None

df_clauses = pd.read_csv("data/clause_json.csv")

clauses = []
for _, row in df_clauses.iterrows():
    clause_flags = _parse_dict(row.get("clause_flags")) or {}
    boundary_strength = row.get("boundary_strength")
    if isinstance(boundary_strength, str) and boundary_strength.strip():
        clause_flags["boundary_strength"] = boundary_strength.strip()

    clauses.append({
        "tokens": _parse_tokens(row.get("tokens")),
        "split": _parse_dict(row.get("split")),
        "boundary_seen": bool(row.get("boundary_seen")),
        "clause_flags": clause_flags,
        "clause_index": row.get("clause_index"),
        "sentence_id": row.get("sentence_id"),
        "file": row.get("file"),
        "tier": row.get("tier"),
        "start": row.get("start"),
        "end": row.get("end"),
    })

parsed = parse_all_clauses(clauses)

def _candidate_conf(candidates, source, default=0.0):
    for item in candidates or []:
        if item.get("source") == source:
            return item.get("conf", default)
    return default

def _boundary_strength(debug):
    strength = debug.get("boundary_reset")
    return strength if strength in {"strong", "weak"} else None

rows = []
for clause_id, clause in enumerate(parsed):
    action = clause.get("action", {})
    agent = clause.get("agent", {})
    patient = clause.get("patient", {})
    debug = clause.get("debug", {})
    candidates = debug.get("agent_candidates") or []
    rows.append({
        "clause_id": clause_id,
        "action_value": action.get("value"),
        "action_conf": action.get("conf"),
        "action_rule": action.get("rule"),
        "agent_value": agent.get("value"),
        "agent_conf": agent.get("conf"),
        "agent_rule": agent.get("rule"),
        "patient_value": patient.get("value"),
        "patient_conf": patient.get("conf"),
        "patient_rule": patient.get("rule"),
        "needs_ml_agent": debug.get("needs_ml_agent"),
        "needs_ml_patient": debug.get("needs_ml_patient"),
        "agent_candidates": debug.get("agent_candidates"),
        "patient_candidates": debug.get("patient_candidates"),
        "topic_conf": _candidate_conf(candidates, "TOPIC", 0.0),
        "last_agent_conf": _candidate_conf(candidates, "LAST_AGENT", 0.0),
        "last_patient_conf": _candidate_conf(candidates, "LAST_PATIENT", 0.0),
        "unknown_conf": _candidate_conf(candidates, "UNKNOWN", 0.10),
        "has_verb": debug.get("verb_index", -1) != -1,
        "verb_index": debug.get("verb_index"),
        "noun_count": debug.get("noun_count"),
        "postverb_is_pt": debug.get("postverb_is_pt"),
        "postverb_pt_resolved": debug.get("pt_resolved"),
        "pt_is_bare": debug.get("r13_reason") == "PT_BARE_NONBLOCKING",
        "boundary_strength": _boundary_strength(debug),
    })

df_parsed = pd.DataFrame(rows)

# --- contexte (2 clauses avant + clause courante, même file) ---
tokens_df = pd.read_csv("data/jsl_tokens_train.csv")
tokens_df["start"] = pd.to_numeric(tokens_df["start"], errors="coerce")
tokens_df["end"] = pd.to_numeric(tokens_df["end"], errors="coerce")

df_clauses["start"] = pd.to_numeric(df_clauses["start"], errors="coerce")
df_clauses["end"] = pd.to_numeric(df_clauses["end"], errors="coerce")
df_clauses["_idx"] = range(len(df_clauses))
df_clauses["_window_start"] = df_clauses["start"]

for file_name, group in df_clauses.groupby("file", sort=False):
    group_sorted = group.sort_values("start")
    idxs = group_sorted["_idx"].tolist()
    starts = group_sorted["start"].tolist()
    for i, clause_idx in enumerate(idxs):
        window_start = starts[max(0, i - 2)]
        df_clauses.loc[df_clauses["_idx"] == clause_idx, "_window_start"] = window_start

contexts = []
for _, row in df_clauses.iterrows():
    file_name = row.get("file")
    w_start = row.get("_window_start")
    c_end = row.get("end")
    if pd.isna(file_name) or pd.isna(w_start) or pd.isna(c_end):
        contexts.append("")
        continue
    mask = (
        (tokens_df["file"] == file_name)
        & (tokens_df["start"] >= w_start)
        & (tokens_df["end"] <= c_end)
    )
    words = tokens_df.loc[mask, "word"].astype(str).tolist()
    contexts.append("/".join(words))

df_parsed["contexte"] = contexts

# --- trivial_unknown filter ---
trivial_unknown = (
    (df_parsed["topic_conf"] == 0)
    & (df_parsed["last_agent_conf"] == 0)
    & (df_parsed["last_patient_conf"] == 0)
)

df_parsed.loc[trivial_unknown, "needs_ml_agent"] = False
df_parsed.loc[trivial_unknown, "needs_ml_patient"] = False

df_parsed.to_csv("parsed_clauses_full.csv", index=False)

df_for_annotation = df_parsed[
    (df_parsed["needs_ml_agent"] == True) | (df_parsed["needs_ml_patient"] == True)
].copy()
df_for_annotation.to_csv("clauses_for_annotation.csv", index=False)

In [108]:
import ast
import json
import pandas as pd

MARGIN_TH = 0.20
TOP2_TH = 0.05
NONUNK_TH = 0.20

df = pd.read_csv("parsed_clauses_full.csv")

def _parse_candidates(value):
    if value is None or str(value).strip() == "":
        return []
    txt = str(value).strip()
    try:
        return ast.literal_eval(txt)
    except Exception:
        try:
            return json.loads(txt)
        except Exception:
            return []

def _extract_confs(cands):
    confs = {
        "TOPIC": 0.0,
        "LAST_AGENT": 0.0,
        "LAST_PATIENT": 0.0,
        "UNKNOWN": 0.0,
    }
    for item in cands or []:
        source = item.get("source")
        if source in confs:
            confs[source] = item.get("conf", 0.0)
    return confs

def _top1_top2(confs):
    vals = sorted(confs.values(), reverse=True)
    top1 = vals[0] if vals else 0.0
    top2 = vals[1] if len(vals) > 1 else 0.0
    return top1, top2

agent_confs_list = []
patient_confs_list = []

for _, row in df.iterrows():
    agent_cands = _parse_candidates(row.get("agent_candidates"))
    patient_cands = _parse_candidates(row.get("patient_candidates"))
    agent_confs_list.append(_extract_confs(agent_cands))
    patient_confs_list.append(_extract_confs(patient_cands))

agent_top1 = []
agent_top2 = []
agent_margin = []
agent_max_non_unknown = []

patient_top1 = []
patient_top2 = []
patient_margin = []
patient_max_non_unknown = []

for confs in agent_confs_list:
    top1, top2 = _top1_top2(confs)
    agent_top1.append(top1)
    agent_top2.append(top2)
    agent_margin.append(top1 - top2)
    agent_max_non_unknown.append(max(confs["TOPIC"], confs["LAST_AGENT"], confs["LAST_PATIENT"]))

for confs in patient_confs_list:
    top1, top2 = _top1_top2(confs)
    patient_top1.append(top1)
    patient_top2.append(top2)
    patient_margin.append(top1 - top2)
    patient_max_non_unknown.append(max(confs["TOPIC"], confs["LAST_AGENT"], confs["LAST_PATIENT"]))

df["agent_top1"] = agent_top1
df["agent_top2"] = agent_top2
df["agent_margin"] = agent_margin
df["agent_max_non_unknown"] = agent_max_non_unknown

df["patient_top1"] = patient_top1
df["patient_top2"] = patient_top2
df["patient_margin"] = patient_margin
df["patient_max_non_unknown"] = patient_max_non_unknown

df["needs_ml_agent_margin"] = (
    (df["agent_top2"] > TOP2_TH)
    & (df["agent_margin"] < MARGIN_TH)
    & (df["agent_max_non_unknown"] > NONUNK_TH)
)

df["needs_ml_patient_margin"] = (
    (df["patient_top2"] > TOP2_TH)
    & (df["patient_margin"] < MARGIN_TH)
    & (df["patient_max_non_unknown"] > NONUNK_TH)
)

def _build_reason(row):
    reasons = []
    if row.get("needs_ml_agent") or row.get("needs_ml_patient"):
        reasons.append("BASE_NEEDS_ML")
    if row.get("needs_ml_agent_margin"):
        reasons.append("MARGIN_AGENT")
    if row.get("needs_ml_patient_margin"):
        reasons.append("MARGIN_PATIENT")
    return "|".join(reasons)

df_margin = df[
    (df["needs_ml_agent"] == True)
    | (df["needs_ml_patient"] == True)
    | (df["needs_ml_agent_margin"] == True)
    | (df["needs_ml_patient_margin"] == True)
].copy()

df_margin["reason_expansion"] = df_margin.apply(_build_reason, axis=1)

# Optionnel: trier par min(agent_margin, patient_margin) croissant
df_margin["min_margin"] = df_margin[["agent_margin", "patient_margin"]].min(axis=1)
df_margin = df_margin.sort_values("min_margin", ascending=True).drop(columns=["min_margin"])

df_margin.to_csv("clauses_for_annotation_margin_v2.csv", index=False)

In [112]:
# df is already loaded in the notebook

# Ensure label columns exist; reload labeled dataset if needed
if "patient labels" not in df.columns:
    df = pd.read_csv("clauses_labels_train.csv")

if "patient labels" not in df.columns:
    if "patient_value" in df.columns:
        df["patient labels"] = df["patient_value"]
    else:
        raise KeyError("Missing 'patient labels' after reload.")
if "agent label" not in df.columns:
    if "agent_value" in df.columns:
        df["agent label"] = df["agent_value"]

df["patient labels"] = df["patient labels"].replace("—", "-")
assert "—" not in set(df["patient labels"].unique())

df["need_patient"] = (df["patient labels"] != "-")

print(df.shape)
if "agent label" in df.columns:
    print(df["agent label"].value_counts())
print(df["patient labels"].value_counts())
print(df["need_patient"].value_counts())

(445, 39)
agent label
UNKNOWN         262
TOPIC            91
LAST_PATIENT     58
LAST_AGENT       34
Name: count, dtype: int64
patient labels
-               220
UNKNOWN         143
TOPIC            63
LAST_AGENT       10
LAST_PATIENT      9
Name: count, dtype: int64
need_patient
True     225
False    220
Name: count, dtype: int64

In [114]:
import pandas as pd
from pathlib import Path

# --- 0) Normalisation minimale (safe) ---
if "patient labels" in df.columns:
    df["patient labels"] = df["patient labels"].replace("—", "-")
df["need_patient"] = (df["patient labels"] != "-")

# --- 1) BONUS FEATURES (AVANT de construire X) ---
df['d_topic_last_agent'] = df['topic_conf'] - df['last_agent_conf']
df['d_topic_last_patient'] = df['topic_conf'] - df['last_patient_conf']
df['d_last_agent_last_patient'] = df['last_agent_conf'] - df['last_patient_conf']

df['discourse_max'] = df[['topic_conf', 'last_agent_conf', 'last_patient_conf']].max(axis=1)
df['discourse_second'] = df[['topic_conf', 'last_agent_conf', 'last_patient_conf']].apply(
    lambda r: r.nlargest(2).iloc[-1], axis=1
)
df['discourse_margin'] = df['discourse_max'] - df['discourse_second']

df['low_discourse'] = (df['discourse_max'] < 0.70).astype(int)
df['no_noun'] = (df['noun_count'] == 0).astype(int)
df['one_noun'] = (df['noun_count'] == 1).astype(int)
df['verb_missing'] = (df['has_verb'] == 0).astype(int)
df['verb_post_pt'] = ((df['has_verb'] == 1) & (df['postverb_is_pt'] == 1)).astype(int)

# --- 2) Feature lists ---
features_agent = [
    'action_conf',
    'topic_conf','last_agent_conf','last_patient_conf','unknown_conf',
    'd_topic_last_agent','d_topic_last_patient','d_last_agent_last_patient',
    'discourse_margin','discourse_max','low_discourse',
    'has_verb','verb_index','noun_count','no_noun','one_noun','verb_missing',
    'postverb_is_pt','postverb_pt_resolved','pt_is_bare','verb_post_pt',
    'agent_top1','agent_top2','agent_margin','agent_max_non_unknown'
]

features_patient = [
    'action_conf',
    'topic_conf','last_agent_conf','last_patient_conf','unknown_conf',
    'd_topic_last_agent','d_topic_last_patient','d_last_agent_last_patient',
    'discourse_margin','discourse_max','low_discourse',
    'has_verb','verb_index','noun_count','no_noun','one_noun','verb_missing',
    'postverb_is_pt','postverb_pt_resolved','pt_is_bare','verb_post_pt',
    'patient_top1','patient_top2','patient_margin','patient_max_non_unknown'
]

# --- 3) Drop colonne vide ---
if 'boundary_strength' in df.columns and df['boundary_strength'].isna().all():
    df = df.drop(columns=['boundary_strength'])

# --- 4) Sanity check colonnes requises ---
missing_a = [c for c in features_agent if c not in df.columns]
missing_p = [c for c in features_patient if c not in df.columns]
print("missing features_agent:", missing_a)
print("missing features_patient:", missing_p)
assert not missing_a and not missing_p, "Certaines features manquent dans df (voir listes ci-dessus)."

# --- 5) Build X / y ---
X_agent = df[features_agent].copy()
X_patient = df[features_patient].copy()

bool_cols = ['has_verb','postverb_is_pt','postverb_pt_resolved','pt_is_bare']
for col in bool_cols:
    if col in X_agent.columns:
        X_agent[col] = X_agent[col].astype(int)
    if col in X_patient.columns:
        X_patient[col] = X_patient[col].astype(int)

X_agent = X_agent.fillna(0)
X_patient = X_patient.fillna(0)

y_agent = df['agent label']
y_patient = df['patient labels']
need_patient = df["need_patient"]

print("n_features_agent:", len(features_agent), "n_features_patient:", len(features_patient))

# --- 6) Leak check (doit être vide) ---
leak_keywords = ['agent_value','agent_rule','agent_conf','patient_value','patient_rule','patient_conf']
leaks = [c for c in list(X_agent.columns) + list(X_patient.columns) if any(k in c for k in leak_keywords)]
print('leak columns in X:', leaks)

# --- 7) Petit print de contrôle ---
print(df[[
    'topic_conf','last_agent_conf','last_patient_conf','unknown_conf',
    'd_topic_last_agent','d_last_agent_last_patient','discourse_margin',
    'noun_count','has_verb','postverb_is_pt','pt_is_bare',
    'agent_margin','patient_margin','agent label','patient labels'
]].head())

# --- 8) Audit outputs (optionnel, report-ready) ---
out_dir = Path("analyse")
out_dir.mkdir(parents=True, exist_ok=True)

def value_counts_pct(s):
    vc = s.value_counts(dropna=False)
    pct = (vc / vc.sum() * 100).round(2)
    return pd.DataFrame({'label': vc.index.astype(str), 'count': vc.values, 'pct': pct.values})

label_dist = pd.concat([
    value_counts_pct(y_agent).assign(variable='y_agent'),
    value_counts_pct(y_patient).assign(variable='y_patient'),
    value_counts_pct(need_patient).assign(variable='need_patient'),
], ignore_index=True)

missing_top15 = df.isna().mean().sort_values(ascending=False).head(15).reset_index()
missing_top15.columns = ['colonne', 'missing_rate']

crosstab_ap = pd.crosstab(df.loc[need_patient, 'agent label'], df.loc[need_patient, 'patient labels'])

label_dist.to_csv(out_dir / "label_distributions.csv", index=False)
missing_top15.to_csv(out_dir / "missingness_top15.csv", index=False)
crosstab_ap.to_csv(out_dir / "crosstab_agent_patient.csv")
print("Saved:", out_dir / "label_distributions.csv")

missing features_agent: []
missing features_patient: []
n_features_agent: 25 n_features_patient: 25
leak columns in X: ['last_agent_conf', 'last_patient_conf', 'last_agent_conf', 'last_patient_conf']
   topic_conf  last_agent_conf  last_patient_conf  unknown_conf  \
0    0.000000         0.686375           0.686375           0.1
1    0.429887         0.686375           0.686375           0.1
2    0.595000         0.595000           0.000000           0.1
3    0.595000         0.595000           0.000000           0.1
4    0.595000         0.595000           0.000000           0.1

   d_topic_last_agent  d_last_agent_last_patient  discourse_margin  \
0           -0.686375                      0.000               0.0
1           -0.256488                      0.000               0.0
2            0.000000                      0.595               0.0
3            0.000000                      0.595               0.0
4            0.000000                      0.595               0.0

   noun_count  has_verb  postverb_is_pt  pt_is_bare  agent_margin  \
0           0      True           False       False           0.0
1           1      True           False       False           0.0
2           1      True           False       False           0.0
3           0      True            True       False           0.0
4           0      True           False       False           0.0

   patient_margin agent label patient labels
0             0.0  LAST_AGENT        UNKNOWN
1             0.0     UNKNOWN              -
2             0.0       TOPIC              -
3             0.0       TOPIC              -
4             0.0       TOPIC        UNKNOWN
Saved: \mnt\data\label_distributions.csv

In [115]:
import pandas as pd
from pathlib import Path
from IPython.display import display, HTML

# Assumes df already loaded and '-' normalized

# Feature selection for ML
features_exclude = [
    'clause_id','action_value','action_rule',
    'agent label','patient labels',
    'agent_value','agent_conf','agent_rule',
    'patient_value','patient_conf','patient_rule',
    'needs_ml_agent','needs_ml_patient',
    'needs_ml_agent_margin','needs_ml_patient_margin',
    'agent_candidates','patient_candidates',
    'contexte','reason_expansion'
]

features_keep = [
    'action_conf',
    'topic_conf','last_agent_conf','last_patient_conf','unknown_conf',
    'has_verb','verb_index','noun_count','postverb_is_pt','postverb_pt_resolved','pt_is_bare',
    'agent_top1','agent_top2','agent_margin','agent_max_non_unknown',
    'patient_top1','patient_top2','patient_margin','patient_max_non_unknown'
]

if 'boundary_strength' in df.columns and df['boundary_strength'].isna().all():
    df = df.drop(columns=['boundary_strength'])

X = df[features_keep].copy()
bool_cols = ['has_verb','postverb_is_pt','postverb_pt_resolved','pt_is_bare']
for col in bool_cols:
    if col in X.columns:
        X[col] = X[col].astype(int)
X = X.fillna(0)

y_agent = df['agent label']
y_patient = df['patient labels']
need_patient = (y_patient != '-')

# 1) dimensions
n_lignes, n_colonnes = df.shape
print(f'dimensions: {n_lignes} lignes, {n_colonnes} colonnes')

# 2) columns + dtypes
dtypes_df = df.dtypes.astype(str).reset_index()
dtypes_df.columns = ['colonne', 'dtype']

# 3) missingness top 15
missing_rate = df.isna().mean().sort_values(ascending=False)
missing_top15 = missing_rate.head(15).reset_index()
missing_top15.columns = ['colonne', 'missing_rate']

# 4) distributions
def value_counts_pct(s):
    vc = s.value_counts(dropna=False)
    pct = (vc / vc.sum() * 100).round(2)
    out = pd.DataFrame({'count': vc, 'pct': pct})
    out.index.name = 'label'
    return out.reset_index()


agent_dist = value_counts_pct(y_agent)
patient_dist = value_counts_pct(y_patient)
need_patient_dist = value_counts_pct(need_patient)

# 5) crosstab agent vs patient (need_patient=True)
crosstab_ap = pd.crosstab(df.loc[need_patient, 'agent label'], df.loc[need_patient, 'patient labels'])

# 6) save outputs
out_dir = Path("analyse")
out_dir.mkdir(parents=True, exist_ok=True)

label_dist = pd.concat([
    agent_dist.assign(variable='y_agent'),
    patient_dist.assign(variable='y_patient'),
    need_patient_dist.assign(variable='need_patient'),
], ignore_index=True)
label_dist.to_csv(out_dir / 'label_distributions.csv', index=False)
missing_top15.to_csv(out_dir / 'missingness_top15.csv', index=False)
crosstab_ap.to_csv(out_dir / 'crosstab_agent_patient.csv')

# Visual check: head of main columns
main_cols = ['agent label', 'patient labels', 'noun_count', 'has_verb', 'verb_index', 'needs_ml_patient', 'needs_ml_agent']
main_cols = [c for c in main_cols if c in df.columns]
head_main = df[main_cols].head(10)

# Compact report: write a small HTML report (no widgets)
def section(title, df_table):
    html = df_table.to_html(index=False)
    return '<details><summary><b>{}</b></summary>{}</details>'.format(title, html)

sections = [
    section('Colonnes + dtypes', dtypes_df),
    section('Missingness top15', missing_top15),
    section('Dist y_agent', agent_dist),
    section('Dist y_patient', patient_dist),
    section('Dist need_patient', need_patient_dist),
    section('Crosstab agent/patient (need_patient=True)', crosstab_ap.reset_index()),
    section('Head colonnes utiles', head_main),
]
report_html = '<h2>Audit report</h2>' + ''.join(sections)
report_path = out_dir / 'report.html'
report_path.write_text(report_html, encoding='utf-8')

# Minimal output in notebook
display(HTML("<a href='analyse/report.html' target='_blank'>Open report.html</a>"))
display(head_main)

dimensions: 445 lignes, 50 colonnes

,agent label,patient labels,noun_count,has_verb,verb_index,needs_ml_patient,needs_ml_agent
0,LAST_AGENT,UNKNOWN,0,True,0,True,True
1,UNKNOWN,-,1,True,0,False,True
2,TOPIC,-,1,True,0,False,True
3,TOPIC,-,0,True,0,False,True
4,TOPIC,UNKNOWN,0,True,0,True,True
5,UNKNOWN,UNKNOWN,0,True,1,True,True
6,UNKNOWN,UNKNOWN,1,True,2,True,True
7,UNKNOWN,-,1,True,0,False,True
8,UNKNOWN,UNKNOWN,1,True,2,True,True
9,UNKNOWN,UNKNOWN,0,True,2,True,True

In [116]:
from pathlib import Path
import pandas as pd
from train_agent_tree import run_agent_tree
from train_patient_tree import run_patient_tree

out_dir = "analyse/agent_v2"
res_agent = run_agent_tree(X_agent, y_agent, out_dir=out_dir)

out_path = Path(out_dir)
expected = [
    out_path / "metrics_agent.csv",
    out_path / "cv_results_agent.csv",
    out_path / "fig_agent_confusion.png",
    out_path / "fig_agent_importances.png",
    out_path / "tree_agent.dot",
    out_path / "tree_agent.png",
]
print("Output files:")
for p in expected:
    print(p, "->", p.exists())

print("\nmetrics_agent.csv:")
print(pd.read_csv(out_path / "metrics_agent.csv"))

print("\nTop 10 importances:")
print(res_agent["feature_importances"].head(10))

out_dir_patient = "analyse/patient_v2"
res_patient = run_patient_tree(X_patient, y_patient, out_dir=out_dir_patient)

out_path_patient = Path(out_dir_patient)
expected_patient = [
    out_path_patient / "metrics_patient.csv",
    out_path_patient / "cv_results_patient.csv",
    out_path_patient / "fig_patient_confusion.png",
    out_path_patient / "fig_patient_importances.png",
]
print("\nPatient output files:")
for p in expected_patient:
    print(p, "->", p.exists())

print("\nmetrics_patient.csv:")
print(pd.read_csv(out_path_patient / "metrics_patient.csv"))

print("\nTop 10 patient importances:")
print(res_patient["feature_importances"].head(10))

c:\Users\Ewan\miniforge3\envs\env_tensorflow\lib\site-packages\numpy\ma\core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,

Best CV metrics:
                                                 best_params  mean_f1_macro  std_f1_macro  mean_accuracy  std_accuracy
{"ccp_alpha": 0.0, "max_depth": null, "min_samples_leaf": 1}       0.357232       0.05412       0.406742      0.038531
classification_report (CV aggregated):
              precision    recall  f1-score   support

  LAST_AGENT       0.23      0.32      0.27        34
LAST_PATIENT       0.32      0.57      0.41        58
       TOPIC       0.24      0.33      0.28        91
     UNKNOWN       0.63      0.41      0.50       262

    accuracy                           0.41       445
   macro avg       0.36      0.41      0.36       445
weighted avg       0.48      0.41      0.42       445

Top 15 feature importances:
                  feature  importance
       d_topic_last_agent    0.201072
             agent_margin    0.156873
               verb_index    0.120583
d_last_agent_last_patient    0.112452
               noun_count    0.072945
           postverb_is_pt    0.052473
                 one_noun    0.050339
          last_agent_conf    0.045988
     d_topic_last_patient    0.045715
               pt_is_bare    0.028711
               agent_top2    0.021744
        last_patient_conf    0.021687
             verb_post_pt    0.013761
     postverb_pt_resolved    0.011638
    agent_max_non_unknown    0.011177
Graphviz export failed: [WinError 2] Le fichier spécifié est introuvable. Dot file saved to \mnt\data\agent_v2\tree_agent.dot
Output files:
\mnt\data\agent_v2\metrics_agent.csv -> True
\mnt\data\agent_v2\cv_results_agent.csv -> True
\mnt\data\agent_v2\fig_agent_confusion.png -> True
\mnt\data\agent_v2\fig_agent_importances.png -> True
\mnt\data\agent_v2\tree_agent.dot -> True
\mnt\data\agent_v2\tree_agent.png -> False

metrics_agent.csv:
                                                    best_params  \
0  {"ccp_alpha": 0.0, "max_depth": null, "min_samples_leaf": 1}

   mean_f1_macro  std_f1_macro  mean_accuracy  std_accuracy
0       0.357232       0.05412       0.406742      0.038531

Top 10 importances:
                      feature  importance
5          d_topic_last_agent    0.201072
23               agent_margin    0.156873
12                 verb_index    0.120583
7   d_last_agent_last_patient    0.112452
13                 noun_count    0.072945
17             postverb_is_pt    0.052473
15                   one_noun    0.050339
2             last_agent_conf    0.045988
6        d_topic_last_patient    0.045715
19                 pt_is_bare    0.028711

c:\Users\Ewan\miniforge3\envs\env_tensorflow\lib\site-packages\numpy\ma\core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,

Best CV metrics:
                                                   best_params  mean_f1_macro  std_f1_macro  mean_accuracy  std_accuracy
{"ccp_alpha": 0.005, "max_depth": null, "min_samples_leaf": 1}       0.378582      0.038217       0.530337      0.048406
classification_report (CV aggregated):
              precision    recall  f1-score   support

           -       0.80      0.55      0.65       220
  LAST_AGENT       0.07      0.30      0.12        10
LAST_PATIENT       0.17      0.67      0.27         9
       TOPIC       0.23      0.24      0.23        63
     UNKNOWN       0.60      0.64      0.62       143

    accuracy                           0.53       445
   macro avg       0.37      0.48      0.38       445
weighted avg       0.62      0.53      0.56       445

Top 15 feature importances:
                  feature  importance
         discourse_margin    0.242802
        last_patient_conf    0.112432
     postverb_pt_resolved    0.089531
     d_topic_last_patient    0.079690
               noun_count    0.072321
          last_agent_conf    0.071448
            low_discourse    0.069186
               verb_index    0.064810
             patient_top2    0.059088
       d_topic_last_agent    0.046628
                 one_noun    0.042811
            discourse_max    0.019162
             verb_post_pt    0.017650
d_last_agent_last_patient    0.012442
             patient_top1    0.000000
Graphviz export failed: [WinError 2] Le fichier spécifié est introuvable. Dot file saved to \mnt\data\patient_v2\tree_patient.dot

Patient output files:
\mnt\data\patient_v2\metrics_patient.csv -> True
\mnt\data\patient_v2\cv_results_patient.csv -> True
\mnt\data\patient_v2\fig_patient_confusion.png -> True
\mnt\data\patient_v2\fig_patient_importances.png -> True

metrics_patient.csv:
                                                      best_params  \
0  {"ccp_alpha": 0.005, "max_depth": null, "min_samples_leaf": 1}

   mean_f1_macro  std_f1_macro  mean_accuracy  std_accuracy
0       0.378582      0.038217       0.530337      0.048406

Top 10 patient importances:
                 feature  importance
8       discourse_margin    0.242802
3      last_patient_conf    0.112432
18  postverb_pt_resolved    0.089531
6   d_topic_last_patient    0.079690
13            noun_count    0.072321
2        last_agent_conf    0.071448
10         low_discourse    0.069186
12            verb_index    0.064810
22          patient_top2    0.059088
5     d_topic_last_agent    0.046628

In [ ]:
import numpy as np
import pandas as pd
from pathlib import Path
from joblib import dump
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix

out_dir_bin = Path("analyse")
out_dir_bin.mkdir(parents=True, exist_ok=True)

y_unknown = (y_agent == "UNKNOWN").astype(int)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
accs = []
f1s = []
precisions = []
recalls = []
cm_total = np.zeros((2, 2), dtype=int)

for train_idx, test_idx in cv.split(X_agent, y_unknown):
    X_train = X_agent.iloc[train_idx] if hasattr(X_agent, "iloc") else X_agent[train_idx]
    X_test = X_agent.iloc[test_idx] if hasattr(X_agent, "iloc") else X_agent[test_idx]
    y_train = y_unknown.iloc[train_idx] if hasattr(y_unknown, "iloc") else y_unknown[train_idx]
    y_test = y_unknown.iloc[test_idx] if hasattr(y_unknown, "iloc") else y_unknown[test_idx]

    model = DecisionTreeClassifier(class_weight="balanced", random_state=0)
    model.fit(X_train, y_train)
    preds = model.predict(X_test)

    accs.append(accuracy_score(y_test, preds))
    prec, rec, f1, _ = precision_recall_fscore_support(y_test, preds, pos_label=1, average="binary", zero_division=0)
    precisions.append(prec)
    recalls.append(rec)
    f1s.append(f1)
    cm_total += confusion_matrix(y_test, preds, labels=[0, 1])

metrics_df = pd.DataFrame([
    {
        "accuracy_mean": float(np.mean(accs)),
        "accuracy_std": float(np.std(accs)),
        "f1_unknown_mean": float(np.mean(f1s)),
        "f1_unknown_std": float(np.std(f1s)),
        "precision_unknown_mean": float(np.mean(precisions)),
        "recall_unknown_mean": float(np.mean(recalls)),
    }
])
metrics_df.to_csv(out_dir_bin / "metrics_agent_unknown_binary.csv", index=False)

cm_df = pd.DataFrame(cm_total, index=["true_non_unknown", "true_unknown"], columns=["pred_non_unknown", "pred_unknown"])
cm_df.to_csv(out_dir_bin / "confusion_agent_unknown_binary.csv")

print("Binary CV metrics:")
print(metrics_df)
print("\nBinary confusion matrix (sum):")
print(cm_df)

final_model = DecisionTreeClassifier(class_weight="balanced", random_state=0)
final_model.fit(X_agent, y_unknown)

feat_names = list(X_agent.columns) if hasattr(X_agent, "columns") else [f"f{i}" for i in range(X_agent.shape[1])]
importances = pd.DataFrame({"feature": feat_names, "importance": final_model.feature_importances_}).sort_values("importance", ascending=False)
print("\nTop 15 importances:")
print(importances.head(15))

fig, ax = plt.subplots(figsize=(4, 4))
im = ax.imshow(cm_total, cmap="Blues")
ax.set_title("Agent UNKNOWN vs non-UNKNOWN")
ax.set_xticks([0, 1])
ax.set_yticks([0, 1])
ax.set_xticklabels(["non-UNKNOWN", "UNKNOWN"])
ax.set_yticklabels(["non-UNKNOWN", "UNKNOWN"])
ax.set_xlabel("Predicted")
ax.set_ylabel("True")
fig.colorbar(im, ax=ax)
fig.tight_layout()
fig.savefig(out_dir_bin / "fig_agent_unknown_binary.png", dpi=150)
plt.close(fig)

top10 = importances.head(10)
fig, ax = plt.subplots(figsize=(6, 4))
ax.barh(top10["feature"][::-1], top10["importance"][::-1], color="#4C78A8")
ax.set_title("Top 10 Importances (UNKNOWN binary)")
ax.set_xlabel("Importance")
fig.tight_layout()
fig.savefig(out_dir_bin / "fig_agent_unknown_importances.png", dpi=150)
plt.close(fig)

dump(final_model, out_dir_bin / "model_agent_unknown_tree.joblib")

In [ ]:
import numpy as np
import pandas as pd
from pathlib import Path
from joblib import dump
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

out_dir_non = Path("analyse")
out_dir_non.mkdir(parents=True, exist_ok=True)

mask = (y_agent != "UNKNOWN")
X_non = X_agent.loc[mask]
y_non = y_agent.loc[mask]

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
accs = []
f1s = []
cm_total = np.zeros((3, 3), dtype=int)
oof_true = []
oof_pred = []
labels = ["TOPIC", "LAST_AGENT", "LAST_PATIENT"]

for train_idx, test_idx in cv.split(X_non, y_non):
    X_train = X_non.iloc[train_idx] if hasattr(X_non, "iloc") else X_non[train_idx]
    X_test = X_non.iloc[test_idx] if hasattr(X_non, "iloc") else X_non[test_idx]
    y_train = y_non.iloc[train_idx] if hasattr(y_non, "iloc") else y_non[train_idx]
    y_test = y_non.iloc[test_idx] if hasattr(y_non, "iloc") else y_non[test_idx]

    model = DecisionTreeClassifier(class_weight="balanced", random_state=0)
    model.fit(X_train, y_train)
    preds = model.predict(X_test)

    accs.append(accuracy_score(y_test, preds))
    f1s.append(f1_score(y_test, preds, average="macro"))
    oof_true.extend(y_test)
    oof_pred.extend(preds)
    cm_total += confusion_matrix(y_test, preds, labels=labels)

metrics_df = pd.DataFrame([
    {
        "accuracy_mean": float(np.mean(accs)),
        "accuracy_std": float(np.std(accs)),
        "macro_f1_mean": float(np.mean(f1s)),
        "macro_f1_std": float(np.std(f1s)),
    }
])
metrics_df.to_csv(out_dir_non / "metrics_agent_nonunknown.csv", index=False)

cm_df = pd.DataFrame(cm_total, index=["true_TOPIC", "true_LAST_AGENT", "true_LAST_PATIENT"],
                     columns=["pred_TOPIC", "pred_LAST_AGENT", "pred_LAST_PATIENT"])
cm_df.to_csv(out_dir_non / "confusion_agent_nonunknown.csv")

print("Non-UNKNOWN CV metrics:")
print(metrics_df)
print("\nConfusion matrix (sum):")
print(cm_df)
print("\nClassification report (OOF):")
print(classification_report(oof_true, oof_pred, labels=labels, zero_division=0))

final_model = DecisionTreeClassifier(class_weight="balanced", random_state=0)
final_model.fit(X_non, y_non)

feat_names = list(X_non.columns) if hasattr(X_non, "columns") else [f"f{i}" for i in range(X_non.shape[1])]
importances = pd.DataFrame({"feature": feat_names, "importance": final_model.feature_importances_}).sort_values("importance", ascending=False)
print("\nTop 15 importances:")
print(importances.head(15))

fig, ax = plt.subplots(figsize=(4.5, 4.5))
im = ax.imshow(cm_total, cmap="Blues")
ax.set_title("Agent non-UNKNOWN")
ax.set_xticks([0, 1, 2])
ax.set_yticks([0, 1, 2])
ax.set_xticklabels(labels, rotation=45, ha="right")
ax.set_yticklabels(labels)
ax.set_xlabel("Predicted")
ax.set_ylabel("True")
fig.colorbar(im, ax=ax)
fig.tight_layout()
fig.savefig(out_dir_non / "fig_agent_nonunknown_confusion.png", dpi=150)
plt.close(fig)

top15 = importances.head(15)
fig, ax = plt.subplots(figsize=(6, 4))
ax.barh(top15["feature"][::-1], top15["importance"][::-1], color="#4C78A8")
ax.set_title("Top 15 Importances (non-UNKNOWN)")
ax.set_xlabel("Importance")
fig.tight_layout()
fig.savefig(out_dir_non / "fig_agent_nonunknown_importances.png", dpi=150)
plt.close(fig)

dump(final_model, out_dir_non / "model_agent_nonunknown_tree.joblib")